### ISSUE TITLE
P.many not available in npm module

### ISSUE THREAD

**Issue by yinso** [jneen/parsimmon#102]
It doesn't look like P.many is available in the published npm module (v.0.9.2), but it's mentioned in [API.md](https://github.com/jneen/parsimmon/blob/master/API.md).

**Comment by wavebeem** [comment]
It's available off of an actual parser, not the Parsimmon object.

P.string('a').many()

**Comment by yinso** [comment]
Ah, I see, thanks for the clarification.

**Comment by wavebeem** [comment]
No problem.
