### ISSUE TITLE
"alt" documentation was a bit confusing for me

### ISSUE THREAD

**Issue by mcapodici** [jneen/parsimmon#109]
Looking at the api doc for `Parsimmon.alt`

It says "This means that the order of parsers matters. If two parsers match the same prefix, the longer of the two must come first. Example:"

```
Parsimmon.alt(
  Parsimmon.string('ab'),
  Parsimmon.string('a')
).parse('ab');
// => {status: true, value: 'ab'}

Parsimmon.alt(
  Parsimmon.string('a'),
  Parsimmon.string('ab')
).parse('ab');
// => {status: false, ...}
```

But the second parse fail is simply due to EOF. I would change the second example to this to make it clearer why the order matters:

```
Parsimmon.alt(
  Parsimmon.string('a'),
  Parsimmon.string('ab')
).skip(Parsimmon.all).parse('ab');
// => {status: true, value: 'a'}
```

Although there might be a more elegant example.

Basically you need the longer string first, because if the shorter string is first then the longer string will never match.

**Comment by wavebeem** [comment]
If I'm understanding this correctly, I think you might prefer an example where it doesn't fail but it's clear that the P.alt parser chose the first (shorter) parser in its list? Like…

```javascript
P.seq(
  P.alt(
    P.string('a').result(1),
    P.string('ab').result(2)
  ),
  P.string('b').result(3).or(P.of(4))
).parse('ab')
```

This results in `[1, 3]` not `[2, 4]`. But I feel like an example of this form would be a lot more complicated.

**Comment by mcapodici** [comment]
Perhaps the simpler original example is better then. Especially for a newcomer who is new to parsing.

How about a slightly more verbose explanation underneath the original code snippet? Such as:

> In the second case, Parsimmon.alt matches on the first parser, and because of this, it doesn't run the second parser at all. This means the combined parser alone reports a success for input 'ab', but there are extra characters left over ('b'). 
> 
> The .parse() method however does a little bit more then just running the parser. It also checks that the end of file has been reached after the parser is run. In the second case the remaining 'b' means that this check fails and so the result is a failure.

What do you think?

**Comment by wavebeem** [comment]
I've just now noticed that there is actually no documentation for the `.parse(str)` method!!! I think that would be a great thing to call out in the `.parse(str)` method, but it's not really that relevant to `Parsimmon.alt(...)` specifically.

**Comment by mcapodici** [comment]
That would be a good idea to mention in .parse.  I can write that documentation if you like and submit pr

**Comment by wavebeem** [comment]
I made a task list on this issue https://github.com/jneen/parsimmon/issues/106.

If you wanna submit a PR for `.parse` documentation then we can close this and I can check off one item.

It would be very appreciated!

**Comment by leonardfactory** [comment]
I think this can be closed now? 👍
