### ISSUE TITLE
New approach for custom parsers

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#111]
I want to take some time to think about the `Parsimmon.custom` API because all the examples I've seen look like:

```javascript
function myCoolP() {
 return Parsimmon.custom(function(ok, fail) {
  return function(str, i){
    if (...) { return ok(...) }
    else { return fail(...) }
  }
}
```

It doesn't seem like we really need two have two nested functions here.

**Comment by wavebeem** [comment]
Off the top of my head something like:

```javascript
function myCoolP() {
 return Parsimmon.custom(function(str, i) {
  if (...) { return [true, ...] }
  else { return [false, ...] }
 })
}
```

or something could be a lot simpler.

**Comment by wavebeem** [comment]
or even just putting all the params together:

```javascript
function myCoolP() {
 return Parsimmon.custom(str, i, ok, fail) {
  if (...) { return ok(...) }
  else { return fail(...) }
 }
}
```

**Comment by jneen** [comment]
I'd be up for putting the params together.

**Comment by wavebeem** [comment]
@jneen Another idea I had: just embrace `Parser(function(str, i))` instead of `Parsimmon.custom` and expose `makeSuccess` and `makeFailure` like you mentioned in the original issue, which honestly seems less complicated.
