### ISSUE TITLE
Switch to exporting Parser itself

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#114]
We should do away with `Parsimmon.Parser` vs `Parsimmon` as two distinct namespaces and just make the current export be the entire `Parser` function, but add on a `Parser.Parser = Parser` for backwards compat.

**Comment by wavebeem** [comment]
Given the backwards compat `Parser.Parser=Parser` thing, this shouldn't even break backwards compat at all, so it could come out before 1.0 if I felt like it.

**Comment by mcapodici** [comment]
Would doing this mean that say you can have:

```
parser = P.string('hello');
parser2 = parser.string('hello2');
```

Unless you set the Parser construction methods to be undefined in the parsers themselves.

**Comment by wavebeem** [comment]
@mcapodici This won't update the the prototype of Parsimmon parsers, just the functions straight off of the Parsimmon library itself.

![image](https://cloud.githubusercontent.com/assets/176815/18841093/75099bc8-83c5-11e6-9520-09e689d7e654.png)

Currently those two objects have totally different things available on them, but my plan is to make them literally the same object.

**Comment by mcapodici** [comment]
Thanks that makes sense to me now. I was confusing myself I think I had to read up on prototypes again.
