### ISSUE TITLE
Basic question: how to best handle this case

### ISSUE THREAD

**Issue by bcherny** [jneen/parsimmon#119]
Hi there, I have a very simple DSL that I'm writing a parser for. However, I'm having trouble coming up with an elegant solution.

The DSL looks like this:

```text
foo
foo or bar
foo or bar or baz
(foo or bar) and baz
```

So the pattern is (ignoring nested expressions and assuming all tuples are of size 1 or 2):

```ts
const word = regex(/.*/)
const separator = alt(
  string('or'),
  string('and')
)
const expression = alt(
  seq(word, separator, word),
  word
)
```

However, `word` also matches ` or ` and ` and `! Words can contain numbers, spaces, and special characters, so I can't just make the regex more specific. What I ended up doing was adding a negative lookahead to the regex: `(?! and )(?! or )`.

Is there a more elegant way to express this, without resorting to negative lookaheads?

Thanks!

**Comment by wavebeem** [comment]
So you want something like this:

```
foo bar and baz quux $$$ nice
```

To turn into something like:

```
["and", ["word", "foo bar"], ["word "baz quux $$$ nice"]]
```

?

What about a word like `core`? That contains `or` but is that allowed?

Is there any more context about the parser you can share with me? Off the top of my head I don't have any great suggestions.

You might be able to use `.chain` to help? https://github.com/jneen/parsimmon/blob/master/API.md#parserchainnewparserfunc

**Comment by bcherny** [comment]
> To turn into something like

Exactly.

> What about a word like core? That contains or but is that allowed?

` and ` and ` or ` are control words as long as they are surrounded by spaces on both sides.

Ideally, I want the program to run something like:

| step | action                       | result                    |
|------|------------------------------|---------------------------|
| 0    | Receive input                | `foo bar and baz quux $$$ nice` |
| 1    | Split by control character   | `{connector: "and", expressions: ["foo bar", "baz quux $$$ nice"]}` |
| 2    | Parse sub-expressions        | `{connector: "and", expressions: [{type: "string", value: "foo bar"}, {type: "string", value: "baz quux $$$ nice"}]` |

**Comment by wavebeem** [comment]
Something like this might be useful to you:

```javascript
var util = require("util")
var P = require("parsimmon")
var _ = P.whitespace

function spaced(parser) {
  return _.then(parser).skip(_)
}

var Word =
  P.regex(/[^ ]+/).chain(w =>
    w === "and" || w === "or"
      ? P.fail("a word")
      : P.of({type: "string", value: w}))

var Phrase =
  P.sepBy1(Word, _).map(words => ({type: "phrase", words}))

var Connector =
  spaced(P.string("and").or(P.string("or")))

var ConnectedExpression =
  P.lazy(() => P.alt(
    P.seqMap(Phrase, Connector, ConnectedExpression, (l, m, r) =>
      ({connector: m, left: l, right: r})
    ),
    Phrase
  ))

var src = "foo bar and quux da$"
var res = ConnectedExpression.parse(src)
if (res.status) {
  console.log(util.inspect(res.value, {depth: null, colors: "auto"}))
} else {
  console.error(P.formatError(src, res))
}
```

## Output

```javascript
{ connector: 'and',
  left:
   { type: 'phrase',
     words:
      [ { type: 'string', value: 'foo' },
        { type: 'string', value: 'bar' } ] },
  right:
   { type: 'phrase',
     words:
      [ { type: 'string', value: 'quux' },
        { type: 'string', value: 'da$' } ] } }
```

If that looks useful, feel free to ask questions and I can dive into more detail later.

**Comment by bcherny** [comment]
This is great, thanks @wavebeem!

So it looks like this is the core of the solution:

```js
var Word =
  P.regex(/[^ ]+/).chain(w =>
    w === "and" || w === "or"
      ? P.fail("a word")
      : P.of({type: "string", value: w}))
```

And the algorithm is:

- For each sequence of characters that does not contain spaces:
  - If the sequence is "and" or "or", then fail so we can try the next parser
  - Otherwise, parse as a word

**Comment by wavebeem** [comment]
Yup! And string together multiple words into phrases, which can be joined by "connectors". If this gets you on the right track, feel free to close the issue. If it doesn't end up working out, feel free to comment in here again and we can talk about it.

**Comment by bcherny** [comment]
It does look like the right track, thanks for the help!

**Comment by wavebeem** [comment]
You're welcome! Best of luck on your parser.
