### ISSUE TITLE
-2+3 = -5 and 0 - -0 = Parse failure (math.js)

### ISSUE THREAD

**Issue by 983** [jneen/parsimmon#135]
```
$ echo "-2+3" > test && node math.js test
[ 'Negate', [ 'Add', [ 'Number', 2 ], [ 'Number', 3 ] ] ]
```

or in other words: -(2 + 3)

I would have expected (-2) + 3 instead:

`[ 'Add', [ 'Negate', [ 'Number', 2 ] ], [ 'Number', 3 ] ]`

Another one:

```
$ echo "0 - -0" > test && node math.js test
Parse failure

{ status: false,
  index: { offset: 4, line: 1, column: 5 },
  expected: [ '\'(\'', 'number' ] }
```

I thought about writing something to generate random math expressions to compare the result to some other parser, but it became too complicated because for example 0--0 is not allowed in JavaScript since '--' is parsed as decrement, so I gave up.

**Comment by wavebeem** [comment]
Good catch, thanks.

**Comment by perlawk** [comment]
It's the problem of precedence, just move the negative to the  top of table:
var table = [
  {type: PREFIX, ops: operators({Negate: '-'})},
  {type: BINARY_RIGHT, ops: operators({Exponentiate: '^'})},
...

when -2^-3 => ^ [ - 2 ] [ - 3 ]
and 4-2^-3  => [- 4  [ ^ 2 [ - 3] ] ] 
as expected.

**Comment by wavebeem** [comment]
Arguably that parse of `-2^-3` is not right, math usually defines that as `-(2^-3)`, but I'm gonna go with it anyway because it's better than the current behavior, and personally makes more sense to me than the normal math version.
