### ISSUE TITLE
Implement Parsimmon.lookahead

### ISSUE THREAD

**Issue by minamorl** [jneen/parsimmon#136]
Hi, I'm very fan of this project.
I'm using this in my product [markdown-next](https://github.com/sketchglass/markdown-next).
At that time I had to implement function like notRegexp.
If you do not mind I'd like to implement `Parsimmon.not` method, which inverts argument parser's sucess and failure.

**Comment by wavebeem** [comment]
Thanks. I looked at your project but didn't see `not` used at all. What's the use case?

I was able to think of something like this?

```javascript
P.string('"')
  .then(P.not(P.string('"')))
  .skip(P.string('"'))
  .parse('"nice"')
// {status: true, value: 'nice'}
```

...instead of the usual regular expression-based approach:

```javascript
P.string('"')
  .then(P.regexp(/[^"]*/))
  .skip(P.string('"'))
  .parse('"nice"')
// {status: true, value: 'nice'}
```

I'm not sure if `P.not`  would make sense for anything besides `P.string`? Do you have more examples?

**Comment by minamorl** [comment]
https://github.com/sketchglass/markdown-next/blob/master/src/parser.ts#L35-L51
I'm using on this lines (this function is almost same as regexp function, except swapping makeSuccess and makeFailure)
This is used in here https://github.com/sketchglass/markdown-next/blob/master/src/parser.ts#L183-L193

The reason why `not` needs is to define parser which check if something continues but should not consume. As you said I think `P.not(P.string('something'))`  is not so useful too. But It is useful to combine with regexp or some more complex parser.

**Comment by wavebeem** [comment]
Oh, so you want this for something like regexp lookahead?

```javascript
"ab".match(/^a(?=b)/)
// => [ 'a', index: 0, input: 'ab' ]
```

Like the `(?=)` part where it matches but doesn't consume?

**Comment by minamorl** [comment]
Yes!
If there is Parsimmon.not it will be so convenient.

**Comment by wavebeem** [comment]
I think I would want to call that `Parsimmon.lookahead` to sound like regexp stuff.

Is something like this what you were thinking of?

```javascript
function lookahead(regexp) {
  // TODO: Wrap regexp with (?: )
  assertRegexp(regexp);
  regexp = RegExp("(?:" + regexp.source + ")", flags(regexp));
  return Parsimmon((str, i) => {
    if (regexp.test(str.slice(i))) {
      return Parsimmon.makeSuccess(i, "");
    }
    return Parsimmon.makeFailure(i, "" + regexp);
  })
}
```

**Comment by minamorl** [comment]
👍 more straightforward than `not` function.

**Comment by wavebeem** [comment]
Would you be interested in working on a pull request to add that function and some tests for it? I can add in the documentation if you'd like.

**Comment by minamorl** [comment]
I'll send PR. Wait a moment please :)

**Comment by wavebeem** [comment]
Looking a bit further, you could just use `P.regexp` with lookahead, like this:

```javascript
someParser.then(P.regexp(/(?=lookahead)/))
```

**Comment by minamorl** [comment]
right, but seems little bit hacky way for me. general users do not know how strings are consumed inside P.regexp function.

**Comment by wavebeem** [comment]
I just meant that .lookahead could just be a shortcut for that. It's
certainly nicer than writing the whole thing 😀

**Comment by minamorl** [comment]
Oh I see :)

**Comment by minamorl** [comment]
```
someParser.skip(P.regexp(/(?=lookahead)/))
```
is nice, but It can be potentially malformed (something like `(` ) so I made it by simple way.
