### ISSUE TITLE
caching?

### ISSUE THREAD

**Issue by mixtur** [jneen/parsimmon#147]
when you implicitly do

```javascript
P.alt(
    A.then(B),
    A.then(C),
    A.then(D)
)
```

A is matched multiple times on the same position with the same result of course.
Can it be cached?

Well, I am sure it can) But it brings two problems to the table. Memory usage, and cache invalidation.

I see two possible strategies.

- cache lives as long as (topmost?) P.alt is working on current position - consuming less memory
- cache lives as long as parser.parse is working - consuming more memory, but can boost performance in other scenarios

UPD:
also the same applies to lookahead, and to any other backtracking

**Comment by wavebeem** [comment]
It is not cached, but in that short example at least, you can just move the `A` outside the `alt`, like:

```js
A.then(P.alt(B, C, D))
```

I'm not even sure it's safe to cache given that custom parsers (`Parsimmon(function(input, i) { ... })`) and custom parser actions (`.map`, `.chain`, etc) exist.

I understand that realistic use cases, usually the `A` part is buried a bit deeper and might be harder to extract at that point, but can you give me an example where this is a problem?

**Comment by mixtur** [comment]
Why wouldn't it be safe? Parsers are basically pure functions. So all the information needed to do caching shoud be on the call stack, right? But of course it will take some effort to track it. Maybe it will outweight performance gains.

It is not a "problem" exactly. But it feels wrong to do the same job over and over again. Example is hard to provide. It is about 600 lines already. And yes it simply has `A` burried somewhere deep.

**Comment by wavebeem** [comment]
The result function in `.map` or `.chain` isn't necessarily pure (though it *really* should be). I'm also not really sure how to best keep track of the repetition, or the performance implications.

And I totally understand the buried `A` problem. I definitely had this issue before with a parser wrapper that added whitespace consumption around other parsers.

**Comment by mixtur** [comment]
If someone relies on parsers being impure, caching will definitely break things.

I don't think repetition can be tracked easily. Not by stack exploration anyway. It has to be some kind of static analysis. Something like https://en.wikipedia.org/wiki/LL_parser#Left_Factoring, I think. But it will require introspection of parsers which is impossible with chains and custom parsers. But even with some false negatives it is still better than nothing. And since it is static it will not impact performance of parsing itself that much.

But may be it is not needed at all. You can simply increase some counter before entering certain parsers and decrease it after existing. While its value is more than zero, other parsers can use their caches. Then if its value is zero those caches can be invalidated.

It shouldn't necessarily be `alt`. It can even be optional. Then it will not break things for those who relies on impure parsers.

**Comment by wavebeem** [comment]
Yeah, we can't statically analyze the grammar, so that's out of the question. 

So only certain parsers could cache? Or you'd have to manually enable caching on a parser?

I'm not certain I understand your counter based approach. I could see potentially something with storing the input and the parse index, along with the parser result, and using that. But I'm not even sure that would be efficient at all.

Honestly, I think we would need a good benchmarking system for both CPU and memory usage before tackling this problem, otherwise we don't know if anything has gotten better or worse from caching work.

**Comment by mixtur** [comment]
Here is what i meant

```javascript
var counter = 0;
var invalidators = [];

function withCachingEnabled(parser, validator, reason) {
    return Parsimmon((input, i) => {
        counter++;
        var result = parser._(input, i)
        counter--;

        if (counter === 0) {
            invalidators.forEach(invalidator => {
                invalidator();
            });
            invalidators = [];
        }
        return result;
    })
}

function withCache(parser) {
    var cache = {};
    var isRegistered = false;
    return Parsimmon((input, i) => {
        if (!counter) {
            return parser._(input, i);
        }
        if (!isRegistered) {
            invalidators.push(() => {
                cache = {};
                isRegistered = false;
            });
            isRegistered = true;
        }
        if (!cache[i]) {
            cache[i] = parser._(input, i);
        }

        return cache[i];
    });
}

```

Then we could do

```javascript
A2 = withCaching(A);
X = P.alt(
  A2.then(B),
  A2.then(C),
  A2.then(D)
);
X2 = withCachingEnabled(X);
```

There should also be some code to handle `throw`s inside parsers. If that happens, we also need to invalidate caches and reset counter.

**Comment by wavebeem** [comment]
I think I see the idea now, though you'd need to store the input also, or otherwise clear the cache between multiple parse calls, which seems difficult.

**Comment by mixtur** [comment]
For each `counter++` there is matching `counter--`. So it reaches zero eventually.
Unless there was some unhandled `throw` in beween. So...

```javascript

function invalidateAll() {
  invalidators.forEach(invalidator => {
    invalidator();
  });
  invalidators = [];
}
function withCachingEnabled(parser) {
    return Parsimmon((input, i) => {
        var result;
        counter++;
        if (counter === 1) {
          try {
              result = parser._(input, i);
          } catch (e) {
              invalidateAll();
              counter = 0;
              throw e;
          }
        } else {
          result = parser._(input, i);
        }
        counter--;

        if (counter === 0) {
          invalidateAll();
        }
        return result;
    })
}
```

I hate rethrows, it makes debugging very awkward. But I don't see the other way.

**Comment by mixtur** [comment]
Oh you mean if someone will invoke parser inside another parser with completely unrelated string. Yeah. That is a problem.

**Comment by mixtur** [comment]
So... to make it work even then, we have to store cache related data somewere else. Let's call that somewhere else "caching context". It should contain counter, invalidators and caches themself. Though if caches are stored in one place invalidators are not needed I think.

The idea is - there can be multiple caching contexts at the same time.

I see two possible strategies of how to use contexts then.

- store contexts in hash table keyed by input, and make sure they exist when they needed.
  - can be slow because inputs can be very long strings. But who knows. Maybe language implementations do that very efficiently.
  - contexts themselves must (probably?) be eliminated after parsing is done.
- create contexts per `parser.parse` invocation, not per input value. And maintain stack of them (along with callstack or explicitly). Then use context from the top of the stack when it is needed.
  - if `parser.parse` will be called with the same string - cache from previous call will be unavailable, though it may contain caches that could be used for current call. Umm... we could scan stack for the already existing inputs and if we found a match use that context instead of new one. But it is the same problem as with first strategy. Inputs are long. Finding match can be slow.

**Comment by mixtur** [comment]
Tried naive caching without contexts. It gave me about x4-x5 speedup, for my stupidly ambiguous grammar at least.

**Comment by wavebeem** [comment]
This seems like a lot of complexity to add to Parsimmon, and I don't want to break backwards compatibility. I think left factoring parsers is a better idea, even if it's tedious sometimes.

**Comment by mixtur** [comment]
Well. At least we know how to do it if you'll change your mind.
