### ISSUE TITLE
post validation

### ISSUE THREAD

**Issue by mixtur** [jneen/parsimmon#148]
If I need to do some "postvalidation" of what was yielded I can only do this

```javascript
parser.chain(x => predicate(x) ? P.succeed(x) : P.fail(description));
```

But if such validation fails Parsimmon will point to position after what was consumed by parser which is confusing.

To avoid that I'll have to do something like

```javascript
P.lookahead(
  parser.chain(x => predicate(x) ? P.succeed(x) : P.fail(description))
).then(parser)
```

It can be wrapped in a helper method, but it will apply parser twice on the same position.

But if it would be implemented in Parsimmon internally it (probably) could simply jump over what was consumed first time and proceed. Also it could look nice:

```javascript
parser.validate(predicate).desc(description);
```

**Comment by wavebeem** [comment]
You could solve this efficiently with a custom parser:

```js
var Parsimmon = require("parsimmon")

function withValidation(parser, validator, reason) {
  return Parsimmon(function(input, i) {
    var result = parser._(input, i)
    if (result.status && validator(result.value)) {
      return result
    } else {
      return Parsimmon.makeFailure(i, reason)
    }
  })
}

var x = 
  withValidation(
    Parsimmon.all,
    function(s) {
      return s === "hey"
    },
    "the word 'hey'"
  )
  .tryParse("hey")

console.log(x)
```

I'm not sure what your use case is, but you might also consider holding off on validation until after parsing.

**Comment by mixtur** [comment]
For example keywords vs variable names. Checking after parsing is an option sometimes, yes.

Wow! I can do `parser._()`! That helps a lot, and fixes my problem. Thank you.

**Comment by wavebeem** [comment]
Yeah, that's what `.parse` uses internally. It's not currently documented, but perhaps it should be, since it's definitely necessary when making custom parsers.
