### ISSUE TITLE
How to parse a series of line breaks 

### ISSUE THREAD

**Issue by user-one** [jneen/parsimmon#149]
I am wanting to take input like this:

```
foo
bar

baz
```
 and transform it into

```html
<p>foo</p>
<p>bar</p>
<p>baz</p>
```

This is the first time I've considered turning to a parsing library for such a task. Here's what I've tried:

```
> linebreak = Parsimmon.regexp(/[^\n]*\n+/)
Parsimmon { _: [Function] }
> linebreak.parse('\n')
{ status: true, value: '\n' }
> linebreak.parse('\n\n')
{ status: true, value: '\n\n' }
> linebreak.parse('\n\n\n')
{ status: true, value: '\n\n\n' }
> linebreak.parse('\n\n\n foo')
{ status: false,
  index: { offset: 3, line: 4, column: 1 },
  expected: [ 'EOF' ] }
> linebreak.parse('\n\n\n foo')
```

This was the first thing I tried:

```coffeescript
a = (text)->
  P.seqMap P.oneOf('\n\n\n'),
    P.oneOf('\n\n'),
    P.oneOf('\n'),
    (first, second, third) ->
      console.log "first: #{first}"
      console.log "second: #{second}"
      console.log "third: #{third}"
  .parse text
```

Ultimately, I want to ignore whitespace and wrap the non-whitespace text with paragraph tags. 
Any kind of help would be appreciated!

**Comment by user-one** [comment]
This seems to do what I want:

```coffeescript
    __.chain profile.about.match(/\b.*/g)
     .filter (str) -> str isnt ''
     .map (w) -> "<p>#{w}</p>"
     .concat()
     .value()
```

**Comment by wavebeem** [comment]
Yup, you can just get it done without using Parsimmon, but if you feel like using Parsimmon, I'd recommend you look at [Parsimmon.regexp](https://github.com/jneen/parsimmon/blob/master/API.md#parsimmonregexpregexp-group0) and [Parsimmon.sepBy](https://github.com/jneen/parsimmon/blob/master/API.md#parsimmonsepbycontent-separator).
