### ISSUE TITLE
[Proposal] Instance based parser framework

### ISSUE THREAD

**Issue by grandsong** [jneen/parsimmon#155]
Let's call Parsimmon '__P__' for short.

When thinking about how to improve P without breaking its API, we will easily get stuck.

So let's unload such burden, take a leap and __imagine__ a brand new 'parser __framework__' named '__Q__', which will inherit whatever necessary and possible from P while bravely change other things.

---

This proposal is a solution for following [CCC](https://github.com/jneen/parsimmon/issues/153) about P:

- The order of rules matters. Use of a rule must go after its declaration and definition, because every rule is a variable.
  As a result, I have to follow a down-top approach when writing rules: when I discover the demand of a new sub rule, I have to move cursor up and write its definition before the use of it.
- `lazy` is for recursive reference. However, it is not recommended.
  I try to use `lazy` as few as possible, but I have to convert existing non-lazy rules to lazy ones when unforeseen recursions occur. I am not so good at predicting, so such changes annoy me again and again.
  Users had better complete design of all rules before using P. Still, it will be a pain to analyze and tell about each rule whether it compose recursions or not. Misses and mistakes will not be uncommon.
- Much work are required to produce typical AST results.
- Codes of rules are lengthy. No way to write (and hence read) rules shortly and concisely, no matter how common their patterns are.
- For a lot of CCC, P is unable to solve them by small improvements. But a loose "salad" is far from a systematic solution.

# Order and `lazy`

For some questions which I listed, what I actually __hope__ is that users don't have to ask or even be aware of such questions (and hence troubles).

When using most parser generators like Nearley, order of rules and recursion are not problems at all.

However, let me take Chevrotain, which is not a parser generator and which shares a lot of common with P, for example.

Look at [Grammars Example/JSON with ES6 syntax](https://github.com/SAP/chevrotain/blob/master/examples/grammars/json/json_es6.js)

You can see `$.object` first appears in Line 75, then it is defined in Line 82, and then used in Line 117. Moreover, `$.value` is defined at last, after all the three uses of it.

All rules are defined as __properties__ of `class JsonParserES6`, and they will be initialized __without__ being fully invoked. So order of defining them are irrelevant.

And the uses of rules are all in sub functions (suck as `{ ALT: () => { $.SUBRULE($.object) } }`). So order of using them are irrelevant as well.

In other words, all rules are __always__ 'lazy'.

## Top-down VS Down-top

Users of Chevrotain are not only saved from confusion and troubles, but also are __encouraged__ to sort their grammar rules __top-down__.

Top-down codes are easy to write and read. It goes in the same direction of the growth of code and therefore is a __very good practice__.

In contrast, with down-top, we have to insert definitions of new functions __before__ where they are first used. Codes are difficult to organize and never feel good when we write and read them.

A little digression: After many years of programming, I have become more and more in favor of top-down approach in my codes. I prefer to define a module as a big object (instead of a big function scope) in which the otherwise down-top, order-sensitive functions are now methods.

Chevrotain is very fast, so I believe the laziness is not an issue of performance. I guess you dislike `lazy` because P has a different architect from Chevrotain and thus has some unique problems.

Let's move on the next topic about architect.

# Namespace VS Instance

P is a namespace (as a toolkit), to which many independent utility functions are attached. It is a typical pure functional programming practice.

However, the purity comes with a cost (or, quite a few costs).

P drags users into a swamp of troubles.

One issue is the order and recursions, as I just talked about.

Another issue is the __absence of properties and configuration (settings)__.

Let me use [Express.js](https://expressjs.com/) as an analogy. It is a famous web framework.

Look at [its API](https://expressjs.com/en/4x/api.html#app).

It begins with `var app = express()` and then all things happen to this `app`.

`app` is a service. It has to be so because it must keep running to monitor many random requests. Parser is uasually stateless and runs far fewer times. But still it can learn from a web service.

The main job of an app is management of routes. And routes have some similarities with grammar rules.

1. Different projects can have different `app`s. And if needed, a project can have multiple applications.

For example, two applications listening to different ports.

2. An Express application can even [have sub-apps](https://expressjs.com/en/4x/api.html#app.mountpath). It's like a parser for one language includes other ones.

It's also a great interest of mine.

An example is that in JS, there can be embedded codes of RegExp, which is a DSL. And for [Reactive.js JSX](https://facebook.github.io/react/docs/introducing-jsx.html) files, the special html template is DSL too.

3. Different applications not only have their own set of routes, but also have their own [Application Settings](https://expressjs.com/en/4x/api.html#app.settings.table).

Some common options are 'etag', 'strict routing'. And for certain users, 'subdomain offset' is a necessity (like domain 'sub.domain.co.jp').

The purist P is incapable of these above. 

# Q

Well, ladies and gentlemen, may I present to you the next parser framework, Q!

## Basic Settings

You may start using it as follows:

```js
var q = Q(); // An instance
q.indexEnabled = true;
q.compose = Q.compose.standard;
```

`q.compose` is a callback used in every rule (except the skipped ones like whitespace) to compose the result.

`Q.compose` is a tiny dictionary/namespace containing two preset callbacks:

1. `Q.compose.standard` is defined as:

	```js
	(name, literal, children, index)=>{
		return {
			name: name, // the rule name
			literal: literal, // the literal consumed
			index: index,
			children: children
		}
	}
	```

	... which is an AST-like node.

2. `Q.compose.simple` is defined as:

	```js
	(name, literal, children, index)=>{
		if(children && children.length){
			return children;
		}
		else{
			return literal;
		}
	}
	```
	... which is just what P produces at present.

If `q.indexEnabled` is `false`, the augument `index` will always be `null` and therefore there will be no waste of computation for `index`.

## Defining rules

Now, let's define the grammar rules.

```js
q.define {
	',': /,\s*/, // comma
	': ': /:\s+/, // colon with whitespace
	'nl': /\n\t*/, // new line
	'{': /\{\s*/, // left brace
	'}': /\s*\}/, // right brace
	'lit-b': /yes|no/
};
```

`q.define` accepts a plain object as a dictionary of rules.

The key (as well as the name) of a rule can be __any__ string. So there's no need to write 'LBrace' for '{'.

If the value of a rule is a RegExp, `P.regexp(regexp)` will be automatically used implicitly. The value can also be a string.

Rules can be accessed directly in `q.rules`.

```js
q.countRules() == 6
typeof q.rules.nl == 'function'

console.log(q.rules.nl.raw);
// /\n\t*/

console.log(q.rules.nl('\n'));
// {name: 'nl', literal: '\n', index: {offset: 0, line: 1, column: 1 }, children: null }
```

## Common Rule Patterns and Short Notations

```js
q.define {
	'lit-s1': /'(?:\\'|[^'])*?'/, // single-quote string
	'lit-s2': /"(?:\\"|[^"])*?"/,
	'lit-s': ['alt', 'lit-s1', 'lit-s2']
};
```

Rule 'lit-s' will actually be:

```js
()=> {
	return p.alt(p.get('lit-s1'), p.get('lit-s1'))
}
```

`q.get(ruleName)` tries to get `q.rule[ruleName]`. If there is no such rule yet, a friendly error will be thrown.

```js
q.define {
	'lit-p': ['seq', '{', 'lit-p-body', '}', {members: 1}], // Note: The last item is not a rule name
	'lit-p-body': ...
};
```

Very readable, isn't it?

'lit-p' means 'literal plain object'. This rule will actually be:

```js
()=> {
	var result = p.seq(p.get('{'), p.get('lit-p-body'), p.get('}'));
	return p.transform(result, {members: 1});
}
```

`q.transform` will add properties to `result` from `result.children` because:

- Not all children are useful. i.e., the two braces.
- Give the useful children meaningful names. i.e., the body of the plain object.

`{members: 1}` means the second child (sub result of rule 'lit-p-body') will become a property named 'member'.

If the argument of `q.transform` is a fuction, then something like `.seqMap` will process `result.children` with the function.

Up to this point, most common needs of AST are satisfied.

Users can always write old P style functions and difine them as rules. No loss of flexibility. Just remember to use `q.get(ruleName)` instead of function variables.

---

The proposal is a modified version of my workaround solution, which works well so far.

**Comment by wavebeem** [comment]
I'm trying to implement a prototype of something like what you're describing and I'm not convinced all of these features are useful enough to add into the main Parsimmon API. If you want to add a `.map` to something based on a regexp, for example, you have to make a change to the global compose function? It's very disconnected.

I started implementing a Lisp parser with a similar function to `define` and already I'm encountering issues because every rule gets wrapped with its name and position, which is not always desired. Follow the gist at the bottom of this post to see what I'm talking about.

I don't think this needs to become stateful/instance based, `define` could simply pass an argument to functions.

Which "function names" can be passed to the array form? It seems to basically be sugar over `alt` and `seqMap`, but it's not entirely clear to me.

https://gist.github.com/wavebeem/fb4e59678095c6a4e915c0f1302b3147

I still think something to wrap all your parsers in lazy is good, but automatically turning these shorthand notations into parsers doesn't seem like a good idea to me. As for your `compose` function idea and automatically adding in the parser name and source location, I think this is a great idea, but I'm not 100% on board with how you're suggesting to implement them.

I don't think Parsimmon will ever be as terse as other libraries, especially like PEG.js. Parsimmon should be understandable as JavaScript code, not a string based language on top of it.

I'm gonna think about this a little bit more and try solving it from a different angle. Maybe one that is actually integrated better with Parsimmon itself to keep this more readable and not stray too far from Parsimmon's composable nature.

**Comment by grandsong** [comment]
Your gist example codes are quite similar to my workaround ones. There is no big difference from yours and mine.

And the details of implementation is not important.

The essence of my proposal is to ease the use by new users with some out-of-box features. As long as most CCCs are dealt with, it will be fine.

P is like a "chassis": well, you can directly ride it, but your user experience can never be as good as riding a "car" (for which Q is one proposal).

---

> ... every rule gets wrapped with its name and position, which is not always desired.

That's exactly why instance is necessary.

A lang parser for Lisp may not need name and position for every rule, while one for Lua may need so.

There should be an option for users to choose. And the option should be stored with the parser instance (whatever you call it) which will then affect every rule.

I find you have much preference (or, inclination) for functional programming even when you have already done much work which is a __weak alternative__ to instance.

`create` returns a `obj` which is an instance in effect. 

There is no need for `getRule` to wrap `obj` in each rule. You simply need to give `obj` a method `getRule`.

`rule(getRule)` is not friendly to users. Such callback should be avoided as possible.

And shorthands make great use of the rules stored as a dictionary in a parser instance. That's the biggest reason why parser generators are so popular.

No wonder you feel instance is useless.

> I don't think Parsimmon will ever be as terse as other libraries, especially like PEG.js. Parsimmon should be understandable as JavaScript code, not a string based language on top of it.

What is good of programming if it ignores common cases and forces users to do chores again, again, and again?

Your experience on parsing Lisp, which is an extreme of language, may have mislead you about in many other languages what patterns are common and how common they are, making you feel shorthands are of low value. Maybe someday you will have real difficulties in writing and reading rules in your function style on a bigger language and then you will feel the pain of absence of concise shorthands.

Shorthands are like auto transmission.

A digression: a few years ago, I struggled a lot when preparing for my driving test for manual transmission cars, which was a common choice in China at that time. After the painful test, driving my car with auto transmission is so easy that I highly regret that I should have took test for auto ones.

Moreover, adding support of shorthand for common patterns of rules won't replace the functions of P which will remain always available. There is no harm to provide more and easier features.

---

I can share my real codes of my workaround in gist, but I don't think it will be more understandable and expressive than what I have already written in this post.

Please reread my post. 

But if you still don't get it, well, let it be.
It's just a loss for future users.
When more users come here, if some give feedbacks, you will probably be more convinced.
I suspect this will happen quite slowly...
Time will tell.

**Comment by wavebeem** [comment]
Here are all the parsers I wrote for [Squiggle](http://squiggle-lang.org/):

- <https://github.com/squiggle-lang/squiggle-lang/blob/master/src/parser.js>
- <https://github.com/squiggle-lang/squiggle-lang/tree/master/src/parse>

And I also wrote a large number of helpers for Parsimmon:

- <https://github.com/squiggle-lang/squiggle-lang/blob/master/src/parse-helpers.js>

Please believe me that I have used Parsimmon for much more complicated uses than parsing Lisp or JSON, I'm just trying to keep examples short here on GitHub.

My biggest problem with the instance approach is then you have to pass the instance around to other files if you want to split up your parser. Trust me that I have felt the pain of ordering rules and splitting up large parsers.

As for wrapping parsers, everything either needs to be a special shorthand or a function anyway so that evaluation can be delayed. For wrapping the output, pretty much every language has a `value` or `expression` parser in at least one area which is just for providing alternatives, and wrapping the output is annoying and wasteful there.

Here is my proposal:

```js
const util = require('util');
const P = require('parsimmon');

// --- Example implementation ---
P.createLanguage = rules => {
  const obj = {};
  Object.keys(rules).forEach(k => {
    obj[k] = P.lazy(rules[k].bind(null, obj));
  });
  return obj;
}

// --- Current definition of mark ---
//
// _.mark = function() {
//   return seqMap(index, this, index, function(start, value, end) {
//     return {
//       start: start,
//       value: value,
//       end: end
//     };
//   });
// };

// Modified version of `.mark` to include node name in it.
P.prototype.node = function(name) {
  return P.seqMap(
    P.index, this, P.index,
    (start, value, end) => ({
      name, start, end, value
    })
  );
};

// --- Definition ---
const Lispy = P.createLanguage({
  Value: r =>
    P.alt(r.Number, r.Symbol, r.String, r.List),

  List: r =>
    r.LParen
      .then(r._)
      .then(P.sepBy(r.Value, r.__))
      .skip(r._)
      .skip(r.RParen)
      .desc('list')
      .node('List'),

  Symbol: () =>
    P.regexp(/[a-zA-Z_-][a-zA-Z0-9_-]*/)
      .desc('symbol')
      .node('Symbol'),

  Number: () =>
    P.regexp(/[0-9]+/)
      .map(Number)
      .desc('number')
      .node('Number'),

  String: () =>
    P.regexp(/"([^"]*)"/, 1)
      .desc('string')
      .node('String'),

  LParen: () => P.string('('),
  RParen: () => P.string(')'),
  _: () => P.optWhitespace.desc('optional whitespace'),
  __: () => P.whitespace.desc('whitespace'),
});

// --- Usage ---
const data = Lispy.Value.tryParse('(nice "code" ( list 1 2 3 ))');
console.log(util.inspect(data, {depth: null}));
```

And here's the output:

```js
var output =
{ name: 'List',
  start: { offset: 0, line: 1, column: 1 },
  end: { offset: 28, line: 1, column: 29 },
  value:
   [ { name: 'Symbol',
       start: { offset: 1, line: 1, column: 2 },
       end: { offset: 5, line: 1, column: 6 },
       value: 'nice' },
     { name: 'String',
       start: { offset: 6, line: 1, column: 7 },
       end: { offset: 12, line: 1, column: 13 },
       value: 'code' },
     { name: 'List',
       start: { offset: 13, line: 1, column: 14 },
       end: { offset: 27, line: 1, column: 28 },
       value:
        [ { name: 'Symbol',
            start: { offset: 15, line: 1, column: 16 },
            end: { offset: 19, line: 1, column: 20 },
            value: 'list' },
          { name: 'Number',
            start: { offset: 20, line: 1, column: 21 },
            end: { offset: 21, line: 1, column: 22 },
            value: 1 },
          { name: 'Number',
            start: { offset: 22, line: 1, column: 23 },
            end: { offset: 23, line: 1, column: 24 },
            value: 2 },
          { name: 'Number',
            start: { offset: 24, line: 1, column: 25 },
            end: { offset: 25, line: 1, column: 26 },
            value: 3 } ] } ] }
```

Any shorthand functions could be implemented on top of that framework as desired. Example:

```js
function either(a, b) {
  return rules => P.alt(rules[a], rules[b]);
}

const lang = P.createLanguage({
  AOrB: either('A', 'B'),
  A: P.string('A'),
  B: P.string('B'),
})
```

I'm not 100% sure about making a library of shorthand functions, but it could easily exist outside this repo and integrate cleanly through the `createLanguage` API.

### Summary

I think this will be my plan going forward.

- Add `Parsimmon.createLanguage` for wrapping `lazy` parsers into an object
- Add `.node` which is like `.mark` but takes a node name too

I understand you may be disappointed, but I am just not a fan of this shorthand notation. I think the solution I'm proposing covers the pain-points of parser ordering and AST construction well while only adding minimal complexity. Additionally, layering your shorthands on top should be totally possible, it just won't be integrated.

**Comment by grandsong** [comment]
> My biggest problem with the instance approach is then you have to pass the instance around to other files if you want to split up your parser.

I don't see yet why passing an instance is a problem while you are happy to pass `ps` in every file in the folder "parse".

In Python, `self` is the first argument of a method. (You can search "(self" in [the official doc](https://docs.python.org/2/tutorial/classes.html) for demo codes.) This demonstrates the relation between functions and methods. In your rule modules (i.e. [array.js](https://github.com/squiggle-lang/squiggle-lang/blob/master/src/parse/array.js)), if `ps` is replaced with `self`, the `exports` will become quite similar to a Python-style method function.

The same story happens to the rules in your proposal:

```js
List: r =>
    r.LParen
      .then(r._)
      .then(P.sepBy(r.Value, r.__))
      ...
```

Replace `r` with `self` and you will get a Python-style method, too.

Why not just accept instance and enjoy its benefits from methods and properties?

## Rule names

In your proposal, codes like `.desc('number').node('Number')` are very verbose and redundant.

Why should users have to write such codes against [the principle "don't repeat yourself (DRY)"](http://programmer.97things.oreilly.com/wiki/index.php/Don%27t_Repeat_Yourself)?

---

If rules are expressed in composition of sub rule names which will be used as __key__ to get these sub rule __properties__, there will no need for `P.lazy` at all.

# Readability vs Flexibility

Functional, verbose codes in your examples are not bad. I suggest shorthands only in order to make codes better.

All roads lead to Rome.

Functional programming codes can accomplish the same objectives as object-oriented ones (in my proposal, however, intance means just semi-OOP).

JS supports multiple paradigms. So it is just a problem of pros and cons between different paradigms.

At cost of "dirtiness", an instance not only shortens codes but also makes them more readable and maintainable. In a word, more user (especially, newbie) friendly.

FP is good for parallel computing, but I assume newbies don't need to worry about that when they just begin learning Parsimmon, so OOP is still preferable for them.

---

JS has an integrated DSL: RegExp. It is very useful and Parsimmon makes good use of it. RegExp greatly eases the way to tell programs what to search or match in strings.

Imagine that RegExp had never been invented and all we had was a utilitiy of many functions for all the text processing tasks. That will be much similar to Parsimmon.

People could live with such toolkit without RegExp; maybe quite happily because they never knew otherwise.

But we do have RegExp and it saves us from a lot of chores.

Consider my proposed shorthands as a simple expression DSL for rules.

---

A downside of RegExp is that it goes too far and its expressions can be insanely unreadable.

On the other hand, as to many parser generators, their rule expressions have quite limited functionalities and therefore lack flexibility.

My proposed shorthands are just JS arrays which will be intelligently parsed to Parsimmon functions. Strings will be taken as sub rule names but many other things are also acceptable. I think it is balanced between readability and flexibility.

# Examples

### Example 1:

```js
  List: r =>
    r.LParen
      .then(r._)
      .then(P.sepBy(r.Value, r.__))
      .skip(r._)
      .skip(r.RParen)
```

can be converted into...

```js
  List: ['seq', 
    '(', '_', 
    ['sepBy', 'Value', '__'],
    '_', ')'
  ]
```

### Example 2:

From [array.js](https://github.com/squiggle-lang/squiggle-lang/blob/master/src/parse/array.js)

```js
function FrozenArray(index, items) {
  return ast.Array(index, true, items);
}

function UnfrozenArray(index, items) {
  return ast.Array(index, false, items);
}

module.exports = function(ps) {
  return P.alt(
    ione(FrozenArray, wrap("[", list0(ps.Separator, ps.Expr), "]")),
    ione(UnfrozenArray, wrap("&[", list0(ps.Separator, ps.Expr), "]"))
  );
};
```

can be converted into...

```js
module.exports = ['alt', 
  ['seq',
    "[", 
    ['sepBy', 'Expr', 'Separator'],
    "]",
    {data: 1, isFrozen: true}
  ],
  ['seq',
    "&[", 
    ['sepBy', 'Expr', 'Separator'],
    "]",
    {data: 1, isFrozen: false}
  ],
];
```

Note, again: 'index' and 'name' will be passed to AST nodes for all rules.

As a result, there will be no need to define an [AST nodes list](https://github.com/squiggle-lang/squiggle-lang/blob/master/src/ast.js) and then import it everywhere.


---

BTW, ...

```js
var list0 = H.list0;
var wrap = H.wrap;
var word = H.word;
...
```

Above codes from [call-or-get.js](https://github.com/squiggle-lang/squiggle-lang/blob/master/src/parse/call-or-get.js) really confuse me.

What's good of them?

# End

Squiggle is a good practical example for newbies to learn about Parsimmon. You may cite it in the homepage of Parsimmon, probably after Common Functions and before Questions.

With Squiggle to learn from, newbies will be much less confused and frustrated. And many will borrow your codes, so my worry about reinventing wheels (especially wrong ones) will be lessened.

So it indirectly solves most of CCCs.

---

My new language will cover nearly all features/rules of Squiggle. I will create a parser fully comparable to yours for Squiggle.

Then, with my codes, I might convince you better. However, there won't be much sense to do so since I can publish my parser on GitHub as a third-party work. Instead, I may suggest you simply cite my work in your doc.

---

Although I fail to convince you for most of my points, our discussions have made me know more and better about Parsimmon and made my thinking much clearer.

Let's stop for now. I will go on with my coding. You can close this post.

**Comment by wavebeem** [comment]
Thank you for your thoughts on Parsimmon. I know we don't agree on everything, but you've helped me to collect my thoughts, and I think I can add some new features to Parsimmon that may be very helpful.

For what it's worth, there are many other parser combinator libraries for JavaScript, so you should check them out and see if they suit you better than Parsimmon.

Have a nice day!

**Comment by grandsong** [comment]
I have checked out most of JS parser libs, and Parsimmon is my best choice. I love it.
