### ISSUE TITLE
Incorrect implementation of applicative apply (ap).

### ISSUE THREAD

**Issue by theqabalist** [jneen/parsimmon#161]
Applicative apply requires that a curried function be provided as the first value being applied to.  The docs and the implementation are reversed from this.  For example a correct example would be

```javascript
P.of(R.add).ap(P.digit.map(Number)).ap(P.digit.map(Number)).parse('53')
// should be {status: true, value: 8}
```

This can be implemented correctly with chain, but it's more verbose.
```javascript
P.of(R.add).chain(add =>
  P.digit.map(Number).map(add).chain(partiallyAdded =>
    P.digit.map(Number).map(partiallyAdded)))
```

Part of the beauty of applicative/monadic parsers is that you can use the applicative semantics to build up an AST as you go.  Without the correct ordering, this is much more painful.

**Comment by theqabalist** [comment]
I realize I jumped the gun, and the behavior specified here complies with fantasy land.  So it's technically not an issue here, sorry for raising it.

**Comment by theqabalist** [comment]
https://github.com/fantasyland/fantasy-land/issues/242 seems to be the relevant discussion if anyone lands here.

**Comment by wavebeem** [comment]
Hmm, no worries! Glad to hear someone is using the fantasy-land compat in Parsimmon though. For what it's worth, I'm almost 100% positive I got confused and expected `.ap` to be reversed also.
