### ISSUE TITLE
TypeError: exports.person.notFollowedBy is not a function

### ISSUE THREAD

**Issue by leonard-thieu** [jneen/parsimmon#162]
Documentation [indicates](https://github.com/jneen/parsimmon/blob/master/API.md#parsernotfollowedbyanotherparser) that `notFollowedBy()` exists but it currently doesn't in the npm package. It looks like it was part of the release of [1.3.0](https://github.com/jneen/parsimmon/blob/365a5e3ff9b3a80638b2b1ecf8b4201abccc9815/CHANGELOG.md#version-130-2017-05-06) but it hasn't been published yet.

Could 1.3.0 be pushed to npm?

**Comment by wavebeem** [comment]
* https://www.npmjs.com/package/parsimmon
* https://unpkg.com/parsimmon@1.3.0
