### ISSUE TITLE
Question about Parsimmon.empty

### ISSUE THREAD

**Issue by gabejohnson** [jneen/parsimmon#165]
What is the reasoning for `empty` being a failure case? I would have expected it to be an alias for `eof`.

**Comment by wavebeem** [comment]
https://github.com/fantasyland/fantasy-land

It's for compatibility with the Fantasy Land API. Sorry for the confusion.

**Comment by gabejohnson** [comment]
I understand the why. But...
```js
Parsimmon.empty = () => Parsimmon.eof;
const p1 = Parsimmon.string('+');
const p2 = Parsimmon.empty();
const s = '+';
p1.concat(p2).parse(s).value === p2.concat(p1).parse(s).value // true
```
Is it not also lawful?

**Comment by wavebeem** [comment]
Unfortunately this would break the second law of monoids and thus make the library not match the Fantasy Land spec: https://github.com/fantasyland/fantasy-land

## Monoid

A value that implements the Monoid specification must also implement the Semigroup specification.

- `m.concat(M.empty())` is equivalent to `m` (right identity)
- `M.empty().concat(m)` is equivalent to `m` (left identity)

**Comment by gabejohnson** [comment]
Didn't check the failure case. Thanks!

**Comment by wavebeem** [comment]
No problem!
