### ISSUE TITLE
npm version of parsimmon

### ISSUE THREAD

**Issue by octomarat** [jneen/parsimmon#179]
Hi,

I have installed parsimmon, wrote some code and then discovered that many functions like .wrap, .trim, .sepBy and so on are missing. They are all included in documentation, but package of version 1.4.0 does not contain them. Am I doing something wrong or the package should be updated?

**Comment by wavebeem** [comment]
https://github.com/jneen/parsimmon/blob/master/CHANGELOG.md

They are not yet released. I'll consider changing the README to point to the latest stable API instead.

**Comment by wavebeem** [comment]
Well, it looks like I forgot to actually run `npm publish` after generating the release. I'll try to remember to publish that tonight.

In the mean time, you could `npm install jneen/parismmon` to pull master straight from the GitHub repo if you want.

**Comment by octomarat** [comment]
Ok, thank you!

**Comment by bd82** [comment]
https://docs.travis-ci.com/user/deployment/npm/

If you have the patience for some devops work 😄

**Comment by wavebeem** [comment]
1.5.0 should be available now. Thanks for bringing this to my attention. https://www.npmjs.com/package/parsimmon
