### ISSUE TITLE
Code coverage (jest?)

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#180]
We should have posted code coverage. Maybe switch to Jest to help facilitate this? idk.

**Comment by wavebeem** [comment]
https://facebook.github.io/jest/docs/migration-guide.html

**Comment by bd82** [comment]
Jest is great, but it does not support browser testing if you ever want to implement such...

see #181 on how to generate code coverage with mocha + istanbul.

To get a badge you will need to upload the data to some code coverage service like
coveralls.io...

**Comment by wavebeem** [comment]
Thanks, this is good to know. I'll hook up coverage reporting through `nyc` for now and look into coveralls soon.
