### ISSUE TITLE
Builtins for line stuff

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#191]
Something inspired by this would be useful:

```js
P.cr = P.string("\r");
P.lf = P.string("\n");
P.crlf = P.string("\r\n");
P.nl = P.alt(P.crlf, P.lf, P.cr).desc("newline");
P.end = P.alt(P.nl, P.eof);
```

**Comment by wavebeem** [comment]
Most parsers can simply leverage `P.end` for all newline-related purposes, and `P.nl` will cover most of the other cases too.

**Comment by mixtur** [comment]
Not sure if definition of P.nl is correct. Is it still new line when it only ends with `'\r'`?

**Comment by wavebeem** [comment]
Mac OS 9 and earlier used that format

**Comment by wavebeem** [comment]
not reeally sure why this is still open. i already fixed it lol.
