### ISSUE TITLE
Integrate Prettier

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#201]

**Comment by bd82** [comment]
You may want to try https://github.com/prettier/prettier
This automatic code formatter remove all the manual work around
keeping a consistent code style.

Write you code however you want and on [file save| before commit] run prettier to
format it to the consistent style.

It can also be used to fail the build if **any** file does not meet the criteria.

**Comment by wavebeem** [comment]
The only reason I haven't pulled in Prettier right now is I don't like how
it reformats method chains in some of the Parsimmon example files, but
thanks for the suggestion. I may consider adding later.

**Comment by bd82** [comment]
I had the same problem with certain constructs being formatted badly in examples.
If it is not a common occurrence you can disable the prettier formatting for specific lines/blocks:
for example: https://github.com/SAP/chevrotain/blob/master/examples/grammars/css/css.js#L295-L303

**Comment by wavebeem** [comment]
Oh, I hadn't noticed that feature. Perhaps I'll give it a shot later when I have some free time. Thanks!

**Comment by wavebeem** [comment]
Taking a look at Prettier again and they must've tweaked the formatting a little bit because all the Parsimmon code looks prefect right now. I think I'll have to pull this in and clean up my ESLint to only cover semantic rules, no style rules. And then make the build also run Prettier.
