### ISSUE TITLE
Question: why is this recursive parser for multi-line comments not working correctly?

### ISSUE THREAD

**Issue by fresheneesz** [jneen/parsimmon#203]
I'm trying to implement nested comments and am running into problems. I don't understand why this parser isn't successfully parsing my input. I would have expected it to match "a[", then fail to match the `any...` line, move on to the alternative `L.test`, match that, then move on to matching the `any...` line once, and then finally match "a]". So why isn't it doing that?

```
var Parsimmon = require("Parsimmon")

var str = Parsimmon.string
var alt = Parsimmon.alt
var seq = Parsimmon.seq
var any = Parsimmon.any


var L = Parsimmon.createLanguage({
    test: function() {
        return seq(
            str("a["),
            alt(
                any.notFollowedBy(str("a]")).notFollowedBy(str("a[")),
                L.test
            ).many(),
            str("a]")
        )
    }
})

console.log(L.test.tryParse("a[ b a[c a] a]"))
```

I'm getting the error:

```
Error: expected not "a[" at line 1 column 6, got '...a[c a] a]'
    at Parsimmon._.tryParse (D:\billysFile\IDEAS\Lima Programming Language\limaParser2-Parsimmon\nod
e_modules\Parsimmon\src\parsimmon.js:362:15)
    at Object.<anonymous> (D:\billysFile\IDEAS\Lima Programming Language\limaParser2-Parsimmon\recur
siveParserTest.js:25:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
```

**Comment by wavebeem** [comment]
the problem is `any.notFollowedBy(str("a]")).notFollowedBy(str("a["))`.

Imagine you're at `a` in the `a[ b a...` string.

`any` will match… then you chain to `notFollowedBy(str("a]"))`. This will be false because there is not an `a]` after the `a`. And the same for `a[`. 

You'll want to use `any` *after* the `notFollowedBy` check. Here's a working example:

```js
var Parsimmon = require("Parsimmon")

var notFollowedBy = Parsimmon.notFollowedBy
var regexp = Parsimmon.regexp
var noneOf = Parsimmon.noneOf
var str = Parsimmon.string
var alt = Parsimmon.alt
var seq = Parsimmon.seq
var notFollowedBy = Parsimmon.notFollowedBy
var any = Parsimmon.any

var L = Parsimmon.createLanguage({
    open: function() {
        return str("a[");
    },
    close: function() {
        return str("a]");
    },
    test: function() {
        return seq(
            L.open,
            alt(
                notFollowedBy(L.open).notFollowedBy(L.close).then(any),
                L.test
            ).many(),
            L.close
        )
    }
})

console.log(JSON.stringify(L.test.tryParse("a[ b a[c a] a]"), null, 2))
```

**Comment by fresheneesz** [comment]
@wavebeem Ok that seems to work. I'm still confused tho. 

You mentioned: 

> `any` will match… then you chain to notFollowedBy(str("a]")). This will be false because there is not an a] after the a. And the same for a[.

So you're saying if I'm here:

```
a[ b a[c a] a]
       ^
```

You're saying `any` will match, and then the `notFollowedBy` will cause that section to fail since there is no "a]" after the "a". But do you mean that it would *succeed* because of that? Looking back at my code, I do see that being a problem, but I would have thought it would have erroneously *matched* instead of erroneously failing. 

But ok, I think I see where the problem is. When it reaches the space here:


```
a[ b a[c a] a]
     ^ 
```

It has no way to continue, because the space can't be matched since a "a[" follows it, and L.test can't match because that section starts with a space. Ok I think I understand now. Thanks!

**Comment by wavebeem** [comment]
ah, yeah, i think that's actually why it's failing there. i was just taking a quick look when I had a minute today. happy to help, and good luck with your parser!
