### ISSUE TITLE
Errors thrown within a parser should be reported with context

### ISSUE THREAD

**Issue by fresheneesz** [jneen/parsimmon#205]
Just like parse failures report the location of the input that caused the failure, errors thrown within a parser should too (whether they're thrown by user code or by internal asserts).

**Comment by jneen** [comment]
Can you give an example, please.

**Comment by fresheneesz** [comment]
Example of error thrown by user code:

```
var Parsimmon = require("Parsimmon")

var parser = Parsimmon.string('foo')
  .map(function(x) {
      throw new Error("test")
      return x + 'bar'
  })

console.log(parser.tryParse("foo"))
```

I've also gotten a lot of the "Error: not a string:" errors from misusing `tie`. I can't quite keep track of how many nested arrays things are returning. Speaking of which, it would be nice if `tie` could work on arbitrarily nested arrays, rather than dying on things like `[ ['a','b','c'], ['d','e'] ]`

**Comment by jneen** [comment]
I'm not sure this is possible without catching and re-raising every possible error? Maybe @wavebeem has ideas?

**Comment by wavebeem** [comment]
Internally I might be able to switch over some of the errors to report the character index where they failed, but as @jneen said I'd definitely need to do some weird hacks to get this for the case you described.

Can you explain more about your experience with `tie` perhaps?

**Comment by fresheneesz** [comment]
Would you be able to do something like this?:

```
_.map = function(fn) {
  try {
    assertFunction(fn);
  } catch(e) {
    return Parsimmon.fail(e.stack) // fail this if you get an exception
  }
  var self = this;
  return Parsimmon(function(input, i) {
    var result = self._(input, i);
    if (!result.status) {
      return result;
    }
    return mergeReplies(makeSuccess(result.index, fn(result.value)), result);
  });
};
```

I can imagine you might need a hard-stop version of `fail` that doesn't allow the parser to continue on another path. But couldn't this technique be done inside a few of the core combinators to make it so you usually get the context in the input file around most exceptions?

My experience with `tie` is that I often have chosen the wrong place to put `tie` and it fails `assertString`. When I get that failure, I have no context around which `tie` call is causing the problem. Stack-trace context around where `tie` was called would help, but I imagine there might be bad performance implications of capturing the stack on every call of a method like `tie` just in case an error happens that would want to have that info. Input file context tho, is available regardless of whether an error happens or not, so we should be able to provide some context to the error message in that way.

**Comment by wavebeem** [comment]
I mean, there *is* stack trace info when these assertions happen, the problem is just that stack traces aren't very useful in Parsimmon since it's generally just filled with `parser._` calls everywhere, since the user calls to the relevant functions are already done. I don't really think there's anything reasonable that can be done about this without just making an entirely new library.
