### ISSUE TITLE
Question: Is there a way to suppress the expectation hints for a particular combinator?

### ISSUE THREAD

**Issue by fresheneesz** [jneen/parsimmon#206]
So I'm building a langauge that has whitespace and comments - weird I know. And I'd like to remove the "expected" results/result for those things. I wrote an `expected` method, would you accept a pull request with this change:

```
_.desc = function(description) {
  return this.expected([description])
};

_.expected = function(expected) {
  var self = this;
  return Parsimmon(function(input, i) {
    var reply = self._(input, i);
    if (!reply.status) {
      reply.expected = [expected];
    }
    return reply;
  });
};
```

This way I can do `combinator.expected([])` to squelch the pieces expected by that combinator.

**Comment by wavebeem** [comment]
I'm guessing you meant to omit the `[ ]` around `[expected]` in the `_.expected` method? Because that's just the current definition of `_.desc`.

Typically what I've done is combine whitespace and comments together into one rule like:

```
P.alt(
  P.whitespace,
  P.regexp(/\/\/[^\n]*/)
).desc("whitespace")
```

and it'll just say "expected whitespace" in that case. And you can always filter out the word whitespace when you're doing your own error reporting at that point.

**Comment by wavebeem** [comment]
Also, I'm glad you've taken an interest in Parsimmon, and I'm always happy to help out with questions and discuss the project, but. You've filed 5 issues in 3 days, many of which seem to be fairly closely related to each other. Please be mindful that I have a full time job and many other obligations, so please try to keep your issues focused as I don't have a lot of time to help.

**Comment by fresheneesz** [comment]
Oops, yes. Meant to have `reply.expected = expected` . But strangely, `combinator.desc([])` squelches the expectation - not how I expected it to work. That's why I thought my code did the right thing.

> combine whitespace and comments together

Yup, exactly what I currently have. But I'd like to squelch even that message (just cause after I've developed the parser, pretty much everywhere can consume whitespace and comments).

> Please be mindful that I have a full time job

I don't mean to disrupt. Feel free to ignore my issues until you have free time. Does it bother you if I file lots of issues you don't have time to take a look at right now?

**Comment by wavebeem** [comment]
> Oops, yes. Meant to have reply.expected = expected . But strangely, combinator.desc([]) squelches the expectation - not how I expected it to work. That's why I thought my code did the right thing.

Oh, that's kinda weird that it worked anyway. Maybe because of how Array.prototype.toString works…

> Yup, exactly what I currently have. But I'd like to squelch even that message (just cause after I've developed the parser, pretty much everywhere can consume whitespace and comments).

I would advise doing custom error reporting inside your parser and filtering it out, probably. But if you could provide more context maybe I could see the value. I never personally removed the whitespace related error messages from my parsers.

> I don't mean to disrupt. Feel free to ignore my issues until you have free time. Does it bother you if I file lots of issues you don't have time to take a look at right now?

Thanks for being considerate 😄  It's mostly that it's hard to keep stuff straight getting a bunch of related issues all at once, but I'll try to relax and get to them as I can.

**Comment by fresheneesz** [comment]
>  if you could provide more context maybe I could see the value

Its mostly that its extraneous information that doesn't usually help figure out why the parsing failure happened. Pretty much all tokens in my language can be separated by whitespace, so its just redundant info that someone who's working with the language should know without being told.

**Comment by jneen** [comment]
If you build a parser in a manner similar to the way described in the walkthrough, I think you'd end up with a parser that looks something like:

``` js
number = regex(/[0-9]+/).skip(whitespace).desc('a number')
lbrack = string('[').skip(newlines).desc('a left bracket')
...
```

which not only allows you to always assume your parsers are properly queued up past whitespace and comments, but also allows you to hide expected values using `.desc`.

**Comment by wavebeem** [comment]
I like that approach, but I've had some issues with it that as soon as you want newline terminated statements or indentation sensitivity, it's really destructive to have the tokens chomping up all your whitespace.

I've been pushing the whitespace into my higher level parsers lately.

**Comment by fresheneesz** [comment]
My language also has whitespace sensitivity, so that's not an approach that would work for me. I'm definitely pushing whitespace into my first-level AST.

**Comment by wavebeem** [comment]
I think I'm gonna say this one should be handled be whatever you use to display errors to your end users. I don't think Parsimmon should be in the business of incorrectly reporting parsing errors.

Obviously if you want to have this feature there's nothing stopping you from monkey patching the prototype to have the method you want.
