### ISSUE TITLE
Feature Request: naughty alt

### ISSUE THREAD

**Issue by fresheneesz** [jneen/parsimmon#207]
I thought I already mentioned this, but i can't find it so maybe not: the "naughty or" (or one might say "naughty alt" in parsimmon's case). This would be a statement that allows some alternatives to be run only when the entire parser has already failed. 

The use case is to make it FAR easier to write good syntax error messages for your parser without making a correctly written program parse any slower. Here's a hypothetical example:

```
alt(string('L'), 
     string('O')).naughtyOr(
     string('0').message("Did you mean the letter 'O'?"),
     string('i').message("Did you mean the letter 'L'?")
   )
```

Where `P.message` would be a method that gives back a message (eg error message) on success of the calling parser, and `naughtOr` would only be run if the entire parser has failed (and has been switched into failure rendering mode then rerun). 

`P.message` could also be tagged with a message type that allows you to add in things like multiple error messages and warnings. Right now, the parser fails on the farthest character parsed, but with `P.message`, Parsimmon parsers could do what gcc does and give you a whole list of errors and warnings from compilation. The idea is that the parser output for a successful run would contain a list of messages, their types, and the line/column they happened on. 

And I suppose that implementing `naughtOr` this way would allow you to have more than 2 rounds of parsing failure (eg if you had a `naughtyOr` called within another `naughtOr`). Not sure where that would be useful (i'm only interested in a 2nd error round), but maybe this would enable some interesting techniques I'm not thinking of. 

Of course this could all be implemented currently by a second stage, as long as you pass the the line/column information into your AST, but it would be way easier to do it natively via `naughtyOr` and `message`. 

Here's some additional discussion: https://github.com/pegjs/pegjs/issues/145 .

Thoughts?

**Comment by wavebeem** [comment]
If I'm understanding this correctly, what you want is already possible:

https://runkit.com/wavebeem/59d2a09e5e849f001285f0a1

**Comment by fresheneesz** [comment]
In that example, the '0' and 'i' parsers are always (or usually) parsed, even for successful parsers. If you have complex parsings for error conditions, that will make parser runs for valid inputs run slower. Also, this technique wouldn't allow you to have errors that your parser can continue passed. An error done in this way will block the parser at that point. 

Here's an example based on yours: https://runkit.com/fresheneesz/59d2a8b35e849f001285f7e5

You can see that even tho the parser is aware that you might have had a typo, it won't tell you that your next character was probably also a typo. You'll have to rerun the parser every single time you make a correction to you code. Often times when working in something like C, you'll write a program, attempt to compile it, find like 100 errors, go through your code fixing the first 10, then rerun. Its a lot faster than doing fix, compile, fix, compile, etc 10 times.

**Comment by wavebeem** [comment]
It does not go down those branches unless the previous branches fail. Look at the console output here:

https://runkit.com/wavebeem/59d2ac170cbb1e0012a53313

> You can see that even tho the parser is aware that you might have had a typo, it won't tell you that your next character was probably also a typo. You'll have to rerun the parser every single time you make a correction to you code. Often times when working in something like C, you'll write a program, attempt to compile it, find like 100 errors, go through your code fixing the first 10, then rerun. Its a lot faster than doing fix, compile, fix, compile, etc 10 times.

I don't see how this is related to naughtyOr. Maybe you could make a separate issue for that? I understand the desire here, but this is going to be a very complicated add.

**Comment by fresheneesz** [comment]
> It does not go down those branches unless the previous branches fail

Sure, but it will go down it when the previous branches fail, even if higher-level alternatives succeed. The whole point of `naughtyOr` is so that those failure parsers aren't touched unless your entire langauge fails first. 

> I don't see how this is related to naughtyOr. Maybe you could make a separate issue for that?

You're right, its not. I'll make a separate issue.

**Comment by wavebeem** [comment]
> Sure, but it will go down it when the previous branches fail, even if higher-level alternatives succeed. The whole point of naughtyOr is so that those failure parsers aren't touched unless your entire langauge fails first.

I guess I'm not really understanding *when* Parsimmon is supposed to use the result of naughtyOr, then. How much higher up does it need to fail for it to go down that branch?

Can you give me a more complete example, because I'm definitely missing the point in your initial snippet.

**Comment by fresheneesz** [comment]
> How much higher up does it need to fail for it to go down that branch?

All the way. The entire `parse` needs to fail before `naughtyOr`s would be called - in an entirely new automatic re-parse. It would be similar to this: https://runkit.com/fresheneesz/59d2b8da5ab12800121b4173

There are a few problems with that example tho:

* I'm keeping global state (I don't think even the state stuff you're talking about allows for safe state like this, does it?)
* Its not recording the line/column info - which would be doable by writing a custom parser (too lazy rn)
* It will also report expectations from the failure mode parser, which it shouldn't do. I could have returned `firstResult` in that last return in `parse`, but then it wouldn't report errors in `naughtOr` parsers. Something more is needed to do that properly

Does this make it a little clearer?

**Comment by wavebeem** [comment]
Hmm, OK this definitely clears up the problem for me now, thanks.

> I'm keeping unsafe global state (I don't think even the state stuff you're talking about allows for safe state like this, does it?)

Right, you should only use *immutable* state, and because of how `withState` works, you kind of get a state layering effect (like scopes), which disappears back up at the top. So that wouldn't work right for keeping track of these potential error messages.

Ultimately, Parsimmon is designed to only track two things: an input string and an index number. Even the line number/column stuff is computed based on the other data. And it's not really designed to keep track of parsing mode or arbitrary data.

I think the best kind of approach would be one where you have an entire parameterized language, maybe? Like:

```js
function blah(hasErrored) {
  function naughtyOr(/* ... */) {
    return hasErrored ? x : y;
  }
  return P.createLanguage({
    /* use `hasErrored` in making your parsers */
    Thing() {
      return naughtyOr(this.A(), this.B());
    }
  });
}

// If parsing fails, call blah(true) afterward and use that parser...
```

As for the stuff about keeping track of multiple error messages, you could have a `SyntaxError` node in your AST with the literal contents of what was gobbled up, and not actually *fail* the parser. Then after parsing you can walk the AST and find the `SyntaxError` nodes and report those. I don't have any experience with recovering from syntax errors and collecting them, though.

**Comment by fresheneesz** [comment]
> Parsimmon is designed to only track two things: an input string and an index number

It also tracks expected values. Couldn't messages be tracked in the same way, except instead of clobbering `messages` like `expected` is in `makeSuccess`, you keep passing them through? Parsing mode could also be tracked this way I think.

> one where you have an entire parameterized language, maybe? 

Sure, that works (except that your example needs `x` to parse in *addition* to `y` when it `hasErrored`), but you'd need to then duplicate the code to create error messages based on those results that give you context in the `input`. And if you implement something like `P.debug`, that code also needs to be duplicated. 

> recovering from syntax errors and collecting them

Isn't that primary purpose #2 of a parser tho? Giving error messages to the programmer is incredibly important. This is why I'm interested in naughtyOr and message - I think it can make doing that easy. 

Perhaps if just a couple lower level things were implemented in Parsimmon, someone could implement `naughtyOr` themselves without building it into the language. I think maybe just these two things would be necessary:

* Adding a static state to be tracked in all makeSuccess or makeFailure results. Eg, you could do something like `language.parse(input, {staticState: {mode: 'failure'}})` to add that key to the failure/success objects
* expose the `formatError` function (and `debug` when it becomes available)

I think with just these two things I could implement a `naughtyOr` combinator. I still would have to create `SyntaxError` nodes and go through the AST to report them, but with an exposed formatError function, I could report those with context in the same way Parsimmon does. Not sure how `debug` would have to be implemented, but I'd imagine similar information could be tracked in a way where I could use `debug` when it becomes available in my second-stage AST traversal.

A third ability would allow me to implement `messages` without a second stage:

* Adding a success state to be tracked in all `makeSuccess` calls. This would be kind of like the inverse of `expected`. Where `expected` is clobbered in `makeSuccess` and passed through in `makeFailure` , this success state would be clobbered in `makeFailure` and passed through in `makeSuccess`. The symmetricalness of this vs `expected` seems appealing. This could be configued like this `language.parse(input, {successState: {key: 'messages'}})`

**Comment by wavebeem** [comment]
> It also tracks expected values. Couldn't messages be tracked in the same way, except instead of clobbering messages like expected is in makeSuccess, you keep passing them through? Parsing mode could also be tracked this way I think.

There are at least 24 parsers in the library defined using the low level `Parsimmon(action)` API, so testing out a change like that is not going to be something that's quick to do. Some of them are rather complicated.

I tried something similar when I was investigating parser state, and it was about a 50% rewrite of the library. I abandoned that branch after several days of headaches because it just felt like a bad approach to me, which is when I got the parameterized language idea (from another project).

> Isn't that primary purpose #2 of a parser tho? Giving error messages to the programmer is incredibly important. This is why I'm interested in naughtyOr and message - I think it can make doing that easy.

Of course, but there's a difference between parsers that stop and report on the first syntax error, vs parsers that attempt error recovery and collect multiple errors to return.

This is a lot different than collecting multiple semantic errors in a well formed parse tree, like linting or type checking.

If you're going to recover from a syntax error and keep going, essentially what you need to do is parse **some** chunk of code that's wrong, pretend everything went OK, consume all of that text input, and leave a note to report it later. Parsimmon can't decide for you what to parse, nor does it really have business tracking that for you.

```js
const P = require("parsimmon");

// Recoverage single line string, in case a user forgets to terminate it.
const L = P.createLanguage({
    String() {
        return P.seqObj(
            ["open", P.string("'")],
            ["content", P.noneOf("'\n").many().tie()],
            ["close", P.any]
        ).node("String").map(obj => {
            if (obj.value.close !== "'") {
                return {
                    type: "SyntaxError",
                    message: `unterminated string: '${obj.value.content}`,
                    start: obj.start,
                    end: obj.end,
                };
            }
            return obj;
        });
    }
});

console.log(L.String.parse("'hello'").value);
console.log(L.String.parse("'oops\n").value);
```

Then after the parse is complete you can walk the tree for SyntaxError nodes. I don't see any reason (right now at least) to stop parsing in Parsimmon and then start over again, while keeping track of modes.

**Comment by fresheneesz** [comment]
"at least 24 parsers in the library defined using the low level Parsimmon(action) API"

Well.. I don't think it would take me more than half an hour to add it... but ok. More of an addition than a rewrite.

"parsers that attempt error recovery and collect multiple errors to return"

The more serious your parser, the more likely it is to do that. 

Anyways, sounds like you've kind of made up your mind. I think I can do what I want with a parameterized language and syntax error nodes in my AST. That will tide me over. If I come up with a better justification while I'm building my language, I'll be sure to post it ; )

**Comment by wavebeem** [comment]
Be my guest and try making a branch with the changes. It was a lot trickier
than I expected when I tried it before. Maybe this one would be less hard,
I don't know.

You could always make your own fork of Parsimmon and show me what you're
thinking and how it applies to the parser you're working on.

**Comment by fresheneesz** [comment]
I'll try that at some point. Will get back to you

**Comment by bd82** [comment]
> If you're going to recover from a syntax error and keep going, essentially what you need to do is parse some chunk of code that's wrong, pretend everything went OK, consume all of that text input, and leave a note to report it later. Parsimmon can't decide for you what to parse, nor does it really have business tracking that for you.

This is essentially correct , the terms I am more familiar with regards to error recovery
speak about modifying the token stream.
* Single Token insertion.
* Single Token deletion.
* Token re-synchronization.

The first problem is that a **PEG** parser does not have a separate tokenizer.
The second problem is that the entire grammar structure must be known in advance to implement most of these heuristics. **Is the grammar structure known in advance with parsimmon**?
Meaning that given a parsimmon parser would it be possible to create an EBNF or visual diagrams of the grammar?

**Comment by fresheneesz** [comment]
I'm realizing that i could use state to track parsing mode too.

**Comment by mixtur** [comment]
> Is the grammar structure known in advance with parsimmon?

The fundamental problem with generating BNF is the fact that `.chain` can execute arbitrary code to return next parser. Fot other combinators, I think it should be possible.

**Comment by wavebeem** [comment]
Yeah, I don't think this is really something Parsimmon can solve for you given its design.

Feel free to leave a comment with a link to a branch that implements what you're proposing and I may take a look at it later, but I'm gonna close this issue for now because I don't think it's going anywhere.
