### ISSUE TITLE
Question: can I specify end of sequence which is already consumed?

### ISSUE THREAD

**Issue by digitalheir** [jneen/parsimmon#211]
Suppose I want to parse a list of digits that must end with a 0 or a 1 (equivalent of `/[0-9]+[01]/`. In my real grammar, specifying a regex is less straightforward):

```
seq(regex(/[0-9]/).many(), regex(/[01]/)).parse("01230")
```

Output:

```
{ status: false,
  index: { offset: 5, line: 1, column: 6 },
  expected: [ '/[01]/' ] }
```

Guess it fails because `/[0-9]/` also applies to the final character, so is already consumed. I would expect / want the system to backtrack however. Is that possible?

**Comment by wavebeem** [comment]
I would use a `.chain` action for this.

```js
P.regexp(/[0-9]{2,}/).chain(s => {
  const c = s.charAt(s.length - 1);
  if (c === "0" || c === "1") {
    return P.of(s);
  }
  return P.fail("blah blah blah");
});
```

**Comment by wavebeem** [comment]
Is this working for you?

**Comment by digitalheir** [comment]
Yes, thank you!!!
