### ISSUE TITLE
Comparison with other parsing libraries

### ISSUE THREAD

**Issue by fresheneesz** [jneen/parsimmon#212]
How would you compare this library to [mona](https://github.com/zkat/mona)? I feel like this and other comparisons would be useful to add, if you/someone has experience with both.

**Comment by wavebeem** [comment]
I played with Mona briefly but I have not used it enough to make a meaningful comparison. Same with Chevrotain. If you have experience with both, I'm happy to accept a PR for the a new markdown document comparing Parsimmon to other libraries.

**Comment by wavebeem** [comment]
I could potentially write a comparison with Jison and PEG.js though. I'm not really sure which parser libraries are popular enough for a comparison document.

**Comment by wavebeem** [comment]
It doesn't really seem like anyone is interested in this making this, and I'm still not. Closing.
