### ISSUE TITLE
Parsing strategy question

### ISSUE THREAD

**Issue by beaugunderson** [jneen/parsimmon#213]
I'm attempting to parse a string of the form:

```
person person description time
```

Where `person` has a specific format, in this case pretend it's `<person:1>`, `description` can contain anything including whitespace, and time is a 'natural time' like `5 days from now`.

My current strategy to get `description` and `time` is this:

```js
export const whatAndWhen = alt(
  seqMap(
    whitespace,
    naturalTime,

    (_, parsedNaturalTime) => parsedNaturalTime
  ),
  any
)
  .atLeast(1)
  .map(result => {
    const what = takeWhile(result, entry => typeof entry === 'string');
    const when = result[what.length];

    return {
      what: what.join('').trim(),
      when
    };
  });
```

I alternate between any character and `naturalTime`, then split them apart in the `.map()`. This gets the job done but I want to know if there's a cleaner way to do it. This parser is also not as strict as I'd like (it would accept multiple natural times).

Ideally I'd like to specify something like this:

```js
seqObj(
  ['what', regex(/.*/)],
  ['when', naturalTime]
)
```

but the regex is greedy and takes the entire string so this doesn't work (and when `/.*?/` is specified it only takes one character).

**Comment by wavebeem** [comment]
I think you can replace `Parsimmon.regex(/.*/)` with `Parsimmon.any.notFollowedBy(naturalTime).many().tie()` which should scan one character at a time, make sure the input isn't a `naturalTime`, accumulate those all into an array, then join it into a string like you wanted.

Let me know if that works for you.

**Comment by beaugunderson** [comment]
Thanks for looking into this! I had tried various incarnations of `notFollowedBy` but not that specific one... Here's what I get for this method:

```js
export const whatAndWhen = seqObj(
  ['what', any.notFollowedBy(naturalTime).many().tie()],
  ['when', naturalTime]
);
```

for a string `'take out the trash on 12/27/2017'` I get this error:

```
expected not "on 12/27/2017" at line 1 column 19, got '...on 12/27/201...'
```

(`on 12/27/2017` is matched by `naturalTime`)

here's [the whole file](https://gist.github.com/beaugunderson/c0370de52a93451c8620cfb6130fc268) just in case this is an issue with `naturalTime` itself, I'll create a very small test case now though just to verify that it will happen with a regular string.

**Comment by beaugunderson** [comment]
ok I get the same behavior with this much smaller test:

```js
import { any, seqObj, string } from 'parsimmon';

const end = string('end of string');

const both = seqObj(
  ['start', any.notFollowedBy(end).many().tie()],
  ['end', end]
);

console.log(both.tryParse('start of string end of string'));
```

**Comment by beaugunderson** [comment]
hm, this works, and is an improvement over what I had! not sure why it works though :)

```js
import { any, seq, seqMap, string, whitespace } from 'parsimmon';

const end = string('end of string');

const both = seq(
  any.notFollowedBy(end).many().tie(),
  seqMap(whitespace, end, (_, parsedEnd) => parsedEnd)
);

console.log(both.tryParse('start of string end of string'));
```

```
[ 'start of string', 'end of string' ]
```

**Comment by beaugunderson** [comment]
when I apply the above method to my `naturalTime` parser some strings parse (an improvement) and some strings don't, however...

**Comment by beaugunderson** [comment]
hmm, I expected this to fix the failing cases but instead it makes all cases fail:

```js
const whitespaceNaturalTime = seqMap(
  whitespace,
  naturalTime,
  (_, parsedNaturalTime) => parsedNaturalTime
);

export const whatAndWhen = seqObj(
  ['what', any.notFollowedBy(whitespaceNaturalTime).many().tie()],
  ['when', whitespaceNaturalTime]
);
```

```
'<staff:1:1|Beau Gunderson> task <patient:2:2|John Doe> description next monday evening'
```

```
expected not " next monday evening" at line 1 column 67, got '... next monday...'
```

**Comment by jneen** [comment]
I highly recommend putting your whitespace handling at the ends of your parsers, rather than the beginning. I don't believe `notFollowedBy` should be necessary for this case (indeed, your format could be parsed with a single regex...)

**Comment by beaugunderson** [comment]
see the gist linked above for naturalTime, super complicated parser that probably could be a regex but handling all the groups would be complicated :)

i’ll try handling whitespace at the end and see if that helps

---

**Comment by beaugunderson** [comment]
hmm, `when` consumes the entire input for both of these:

```js

export const whatAndWhen = seqObj(
  ['what', any.many().tie().skip(whitespace)],
  ['when', naturalTime]
);

export const whatAndWhen = seqObj(
  ['what', seq(any.many().tie(), whitespace)],
  ['when', naturalTime]
);
```

```
expected one of any character, whitespace, got the end of the input
```

**Comment by jneen** [comment]
`any.many()` is always going to consume the entire input...

**Comment by jneen** [comment]
parsimmon parsers are always greedy, and will not be tried more than once to find more creative backtracks. in that way parser combinators are more similar to a PEG model. Maybe try `notChar('<').many().tie()`?

**Comment by jneen** [comment]
Rule of thumb: if you call `.many()` on a parser that can never fail, you are either going to have an error (or infinite loop?) or consume the entire input, neither of which are things you probably want to do.

**Comment by wavebeem** [comment]
@jneen currently it will be an infinite loop to do like `P.string('').many().parse('')`, but https://github.com/jneen/parsimmon/pull/198 is open to change that.

**Comment by jneen** [comment]
Right. But it stands that `.many()` on a parser that cannot fail is probably the wrong thing.

**Comment by beaugunderson** [comment]
@jneen everything you wrote makes sense, thank you for explaining!

it seems like the best I can do then, to parse a string that can contain anything, but should end with a known pattern, is this:

```js
export const whatAndWhen = alt(whitespace.then(naturalTime), any)
  .atLeast(1)
  .map(result => {
    const what = takeWhile(result, entry => typeof entry === 'string')
      .join('')
      .trim();
    const when = result[what.length];

    return { what, when };
  });
```

**Comment by wavebeem** [comment]
Looks like this is resolved now so I'm closing the issue.
