### ISSUE TITLE
Question: advise to implement 'endBy1'.

### ISSUE THREAD

**Issue by karak** [jneen/parsimmon#215]
Hi.

I love parser combinators and I'm trying to introduce 'endBy1' feature to parsimmon for my work.

Note: endBy1 in Parsec is [HERE](https://hackage.haskell.org/package/parsec-3.1.11/docs/src/Text.Parsec.Combinator.html#endBy1).

My implementation that follows works, but has some problems.

#### 1. Efficiency

The `parse` method calls its callback many times with varying `i` to call `terminator._()` at same conditions as many times.

#### 2. Error reporting

I'm unsure about appropriate arguments of `makeFailure`.

Could someone helps?

----

```addon.js
/**
 * add endBy1 methods to parsers.
 *
 * @param {Parsimmon} P
 */
module.exports = function (P) {
  P.prototype.endBy1 = function (terminator) {
    return P((input, i) => {
      let result1;
      let result2;
      for (let j = i; j < input.length; j += 1) {
        result2 = terminator._(input, j);
        if (!result2.status) {
          result1 = null;
          continue;
        }
        result1 = this._(input.substring(0, j), i);
        if (!result1.status) {
          continue;
        }
        return P.makeSuccess(result2.index, [result1.value, result2.value]);
      }

      if (result2.status) {
        return P.makeFailure(input.length, result2.expected);
      } else {
        return P.makeFailure(i, result1.expected);
      }
    });
  };
};

```

**Comment by wavebeem** [comment]
If I'm understanding this correctly:

```js
p1.endBy1(p2)
```

would be equal to

```js
p1.atLeast(1).skip(p2)
```

Is that right?

**Comment by karak** [comment]
That's it!
I missed `atLeast()`, which could substitues `many1()`.
So, implementation is surely easy.

**Comment by karak** [comment]
I published my private toolbox as a plug-in.  That file is at [Github](https://github.com/karak/parsimmon-addon-combinators/blob/master/src/index.ts).

The last `manyTill` method could have more efficient implementatioin....

**Comment by wavebeem** [comment]
I appreciate the thought behind this but I think I'd like to stick with the current approach seeing as it's still fairly short and Parismmon's API is quite large
