### ISSUE TITLE
Question: markdown parsing

### ISSUE THREAD

**Issue by ivan-kleshnin** [jneen/parsimmon#216]
I'm trying to make a markdown parser for learning purposes (I understand that the full spec is tricky, so I pick just the simplest elements).

Here is my code

```js
import OS from "os"
import P from "parsimmon"
import Util from "util"

let char = P.regex(/./)        // any char except line breaks
let chars = P.regex(/.+/)      // sequence of chars except line breaks
let spaces = P.regex(/[ ]+/)   // sequence of at least one space
let LB = P.regex(/\r\n|\r|\n/) // line break
let PB = LB.atLeast(2)         // paragraph break
let SLB = LB.notFollowedBy(LB) // single line break
let lines = chars.sepBy(LB).map(x => x.join(OS.EOL))

let Markdown = P.createLanguage({
  Header: (r) => {
    return P.seqMap(
      P.regex(/#{1,6}/), spaces, chars,
      (init, _, text) => {
        let tagName = `h${init.length}`
        return `<${tagName}>${text}</${tagName}>`
      }
    )
  },

  UnorderedList: (r) => {
    return P.seqMap(
      P.string("*"), spaces, chars,
      (_, __, text) => {
        return `<li>${text}</li>`
      }
    )
    .sepBy(LB)
    .tie()
    .map(x => {
      return `<ul>${x}</ul>`
    })
  },

  Paragraph: (r) => {
    return lines
      .map(text => {
        return `<p>${text}</p>`
      })
  },

  File: (r) => {
    return P.alt(r.Header, r.UnorderedList, r.Paragraph)
      .sepBy(PB)
      .trim(P.optWhitespace)
  }
})

let code1 = `
# Header

p1-1
p1-2

p2-1
p2-2

* foo
* bar
`

console.log(Markdown.File.tryParse(code1))
```

My general problem is that I can make every parser work in isolation but when, then, I combine them together – something fails. I suspect that's because my parsers are too whitespace-greedy but I'm not sure how to prove it.

**For example:**

```js
File: (r) => {
    return P.alt(r.Header, r.Paragraph)
      .sepBy(PB)
      .trim(P.optWhitespace)
  }
```

outputs

```
[ '<h1>Header</h1>',
  '<p>p1-1\np1-2</p>',
  '<p>p2-1\np2-2</p>',
  '<p>foo\nbar</p>']
```
 
as expected. When I add some parser that spans over lines like 

```js
File: (r) => {
    return P.alt(r.Header, r.UnorderedList, r.Paragraph)
      .sepBy(PB)
      .trim(P.optWhitespace)
  }
```

it fails 

```
Error: expected one of '*', /#{1,6}/, /\r\n|\r|\n/, EOF at line 4 column 1, got '...p1-1

p2-1
p...'
```

and I can't make it work. When I isolate it like: 

```js
File: (r) => {
  return P.alt(r.UnorderedList)
    .sepBy(PB)
    .trim(P.optWhitespace)
  }
})

...

let code1 = `
* foo
* bar
`
```

The parsing works again:

```js
[ '<ul><li>foo</li><li>bar</li></ul>' ]
```

Any advices are welcome.

**Comment by anko** [comment]
If you're on Windows, maybe it's the [newline representation](https://en.wikipedia.org/wiki/Newline)?

```js
let LB = P.regex(/\r\n|\r|\n/) // line break
let PB = LB.atLeast(2)         // paragraph break
let SLB = LB.notFollowedBy(LB) // single line break
```

↑ `PB` can match a single `\r\n` line break sequence in Windows.

Try replacing your input's `\r\n`-occurrences with `\n` first.

**Comment by ivan-kleshnin** [comment]
I'm on Mac. Tried with `let LB = P.regex(/\n/)`, got the same result.

https://gist.github.com/ivan-kleshnin/80ad8070b618494c0c26976ba0609133

**Comment by wavebeem** [comment]
The problem is you need to use `.sepBy1` inside `UnorderedList` and in `lines`. Your `UnorderedList` parser allows `""` as a valid unordered list, so it detects a list and then gets confused.

**Comment by wavebeem** [comment]
As a general rule, parsers that can match 0 characters are extremely dangerous, and should always come **after** other parsers.

**Comment by ivan-kleshnin** [comment]
Got it. Thank you!
