### ISSUE TITLE
Support fantasy-land Contravariant class.

### ISSUE THREAD

**Issue by theqabalist** [jneen/parsimmon#236]
So, being that a `Parser a` is essentially a `StateT s (Either failure) a`, and StateT is an instance of Contravariant, it seems like it would be helpful to implement `.contramap` in case you want to be able to modify the input before the parser runs.

This is fairly easy to do naively.  My question is, is the extra work worth it to try to maintain positional parity between the original input and the modified input since parser failures would be against the modified input, rather than the original input.  Or should contramap just map the input and run the parser against that.

This is actually of use to me currently (I would like to map input, specifically `binaryParser.contramap(x => Buffer.from(x, 'base64')` so that I can accept base64 encoded strings.  So it's not just an intellectual implementation.

In my case, positional parity between the index of the base64 string and the buffer is irrelevant, but in other mappings, I can see it being relevant, hence why I am starting this discussion before I just submit a naive PR implementation.

**Comment by wavebeem** [comment]
I've never heard of "contravariant" before so I just looked at the fantasy-land page but I didn't quite understand what the point of it is.

Is the idea that `oldParser.contramap(f)` returns a new parser where `newParser.parse(x)` is equivalent to `oldParser.parse(f(x))`?

**Comment by theqabalist** [comment]
That is correct in the equivalence.

Covariant functors, or what are normally referred to as just "functors" capture the idea of producing a value.  Contravariant functors capture the idea of consuming a value.  A generalized "Predicate" of type `a -> Bool` for example, is a contravariant functor in `a`.  Functions have the special concept of both consuming a value and producing a value, so a function from `a -> b` is covariant in b and contravariant in a.  This relationship is known as a profunctor.  Profunctors are pretty interesting things (you can build lenses out of them, for example), but I have not run into anything at this point what would make me want to treat a parser like a profunctor.  However, the idea of slightly or totally modifying the input of a parser before it runs does seem like something that would be useful, and as I mentioned earlier, is something I want to do so that I can hide the conversion details of the encoding into the parser instance through its denotative construction, rather than a detail littered in another place in the code base.

What I am unsure of is whether or not the semantics would imply that you maintain a positional mapping between `input` and `f(input)` because for something like basic encoding, or compression, there is no positional relationship between `f(input)` and `input` that makes any sense.  However, if you were to write a javascript parser, and you wanted to preprocess with babel from es6 to es5 so your es5 parser could understand, the concept of a source map comes to mind so that parsing errors could refer to their original positions.

But now, in thinking about it, because the parser is only consuming the final output of the contramaps, perhaps it makes sense that the burden is on the map functions to produce input that can be parsed, rather than on the parser to unmap the input (which would require full isomorphisms rather than just functions).

**Comment by wavebeem** [comment]
I can sort of see the point on something like your base64 example for the binary parser—though it's really just a little sugar over .parse or .tryParse.

But yeah I don't even see a way you could get Parsimmon to report back position information at all without some kind of `f` that returns a string with in-band encoding of previous locations.

**Comment by theqabalist** [comment]
I think, to try to make it more concrete, an important aspect that goes slightly beyond just sugar is that it encapsulates the transformation into the data type itself.  So, like in my case, I get a webhook that gets two fields, `payloadType` and `payloadData`.  The former can be `ascii` or `binary` and the latter can be csv or base64.  Without something like contramap, I have to make two decisions: which parser to use, and how to preformat the payload.  If I contramap my binary parser with decoding, then I can more elegantly make a single decision: which parser to load, because the the payload is then passed directly to the parser.

If you're OK with it, I would like to PR a contramap implementation that doesn't do the crazy positional tracking, because I think in most cases that will be sufficient.  If, for whatever reason, people start using it heavily and it comes up consistently that positional parity is important, we can always address that later.

**Comment by wavebeem** [comment]
looks like this should've been closed by https://github.com/jneen/parsimmon/pull/237
