### ISSUE TITLE
Stop including Node polyfills in the built JS

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#238]
https://webpack.js.org/configuration/node/

Apparently webpack polyfills a few node things by default.

This includes a Buffer polyfill which is pretty cool, it's self-contained so I'd have to go out of my way to pollute global `Buffer` to actually let people use it. And even then it only works in browsers with arraybuffers or whatever.

So yeah this is bloating the built JS file and let's turn it all off with `node: false` in the webpack config.

**Comment by wavebeem** [comment]
At a quick glance I think this will cut the bundled JS from ~34kb to ~11kb!!

**Comment by makoven** [comment]
..and now it can not be used without a webpack at all. Because feross's standalone bundle does not work in the browser
https://github.com/feross/buffer

**Comment by wavebeem** [comment]
Hmm, looks like there's a bug somewhere in the code setup. If you define `window.Buffer = {}` the code should stop crashing. Can you open a new bug about the issue you're seeing, please?

**Comment by makoven** [comment]
@wavebeem 
https://github.com/jneen/parsimmon/issues/282
