### ISSUE TITLE
Error formatting improvements

### ISSUE THREAD

**Issue by halfzebra** [jneen/parsimmon#239]
I'm creating this issue to document the feature discussed in #143 about the improvements for the error formatting.

Here's the example of the proposed error format:

<img width="545" alt="screen shot 2018-04-05 at 09 21 28" src="https://user-images.githubusercontent.com/3983879/38413226-6294a898-398b-11e8-8c1d-1e58b1669738.png">

**Comment by wavebeem** [comment]
I just noticed a bug where the arrow is misaligned for binary parsers:

```
-- PARSING FAILED --------------------------------------------------

> 00 | 01 00 00 02  00
     |             ^^
```

It seems to not be taking into account the two space gap in the middle. @halfzebra do you want to look into the bug or should I?

**Comment by halfzebra** [comment]
@wavebeem I will be able to address this only in 6-7 hour from now.

I'll do it later today if this is not super urgent.

**Comment by wavebeem** [comment]
No rush at all, just wanted to ask if you wanted to look at it

**Comment by halfzebra** [comment]
Addressed the bug in #262y, please let me know if there's anything else! 🙂

**Comment by wavebeem** [comment]
I think we're all good. I'll close this issue and merge the PR and do a release when I get some time. Thanks!
