### ISSUE TITLE
Add match group parameter to regexp()

### ISSUE THREAD

**Issue by Bartvds** [jneen/parsimmon#24]
Currently the regexp parser returns the whole match, while it would be very convenient if we could specify a match group.

Good for optional stuff in the RegExp: so if you have like `/v?(\d+)/` you could get just the digits and ignore the 'v' prefix.

I have this working [here](https://github.com/Bartvds/parsimmon/blob/46b08b9da0fa6b03af663021703ca8d7c70d2275/src/parsimmon.js#L266-L298). (looks funny because it optimises a conditional). Got some tests too.

I can PR this but since you guys are working on parsimmon I'd send a ticket first as I worked on the old error-throwing code.

**Comment by wavebeem** [comment]
I'm voting to keep the regexp parser simple.
