### ISSUE TITLE
Quiz Parser (question)

### ISSUE THREAD

**Issue by ivan-kleshnin** [jneen/parsimmon#247]
Good day! The following parser is made to parse quiz DSLs like:

```
( ) Foo
(x) Bar

- or -

[x] Foo
[x] Bar
```

```js
let P = require("parsimmon")

let isXBullet = (bullet) => bullet == "(x)" || bullet == "[x]"

let sentence = P.noneOf("\n\r()[]").atLeast(1).tie()

let monoBullet = (mustBeFilled = null) => {
  if      (mustBeFilled === true)  return P.string("(x)")
  else if (mustBeFilled === false) return P.string("( )")
  else                             return P.alt(P.string("(x)"), P.string("( )"))
}

let multiBullet = () => {
  return P.alt(
    P.string("[x]"),
    P.string("[ ]"),
  )
}

let monoOption = (mustBeFilled = null) => {
  return P.seq(monoBullet(mustBeFilled), sentence)
}

let multiOption = () => {
  return P.seq(multiBullet(), sentence)
}

let monoOptions = (mustBeFilled) => {
  function go(mustBeFilled, z) {
    return monoOption(mustBeFilled).chain(([bullet, sentence]) => {
      z = [...z, [bullet, sentence]]
      let hasXBullet = Boolean(z.find(([b, _]) => isXBullet(b)))
      if (hasXBullet) {
        return P.alt(
          go(false, z),
          P.of(z)
        )
      } else {
        return P.alt(
          go(null, z),
          P.fail("mono quiz must have a single X bullet") // !!!
        )
      }
    }).trim(P.optWhitespace)
  }

  return go(mustBeFilled, [])
}

let multiOptions = (mustBeFilled) => {
  return P.sepBy1(multiOption(), P.whitespace)
}

let quizLang = P.createLanguage({
  quiz: function (L) {
    return P.alt(
      monoOptions(null),
      multiOptions(),
    ).trim(P.optWhitespace)
  },
})

let expr1a = `
( ) foo
(x) bar
( ) baz
`

let expr1b = `
( ) foo
( ) bar
( ) baz
`

let expr2b = `
(x) foo
( ) bar
(x) bar
`

let expr3b = `
(x] foo
( ) bar
( ) bar
`

console.log("1a")
console.log(quizLang.quiz.parse(expr1a))

console.log("1b")
console.log(quizLang.quiz.parse(expr1b))

console.log("2b")
console.log(quizLang.quiz.parse(expr2b))

console.log("3b")
console.log(quizLang.quiz.parse(expr3b))
```

It works. The issue I have is an error notification, check the line marked as  `!!!` above.
For the following invalid case:

```
( ) Foo
( ) Bar
```

I'd like to see a message like 

```
mono quiz must have a single X bullet
```

What I get instead is `expected: [ '\'( )\'', '\'(x)\'' ]` which is kinda valid because it kinda means "continue or finish – it's not finished now". Anyway, I'd like to understand more about Parsimmon failures so I ask you guys to advice on that. 

1. Is it possible to upstream the above `P.fail` error message somehow?
I also tried `P.alt(...).desc(__)` but it obviously cloaks other important errors like unpaired brackets.

2. Is it possible to achieve the same functionality without a recursion?

**Comment by wavebeem** [comment]
Hi!

1.  Yeah, that's just how descriptions work, I think? I'm not really sure there's any way to get what you want.

2.  Probably not, but I would personally approach this problem in two phases.

    1.  Parse all the options, even if they checked too many, and make a data structure you can easily use later.

    2.  Write code that uses the data structure to report semantic errors "You filled in too many answers in a `( )` section"

Something maybe like…

```js
({
  type: "Quiz",
  items: [
    {
      type: "MultiGroup",
      items: [
        { type: "MultiGroupItem", checked: true },
        { type: "MultiGroupItem", checked: false },
        { type: "MultiGroupItem", checked: false },
        { type: "MultiGroupItem", checked: true },
        { type: "MultiGroupItem", checked: false }
      ]
    }
    {
      type: "SingleGroup",
      items: [
        { type: "SingleGroupItem", checked: true },
        { type: "SingleGroupItem", checked: false },
        { type: "SingleGroupItem", checked: true }
        // ^ report error since we already found a `true` in this group
      ]
    }
  ]
})
```
Feel free to ask more questions. I hope this feedback is helpful. 😁

**Comment by ivan-kleshnin** [comment]
So you would remove those checks from the parsing step? It will certainly make thing easier but will remove the ability to reference an offset. Or maybe it's possible to keep those for later use with https://github.com/jneen/parsimmon/blob/master/API.md#parsermark ?!

**Comment by wavebeem** [comment]
Exactly! I would highly recommend using [`.node` ](https://github.com/jneen/parsimmon/blob/master/API.md#parsernodename) on almost every parser you make.

`.mark` as you mentioned is good too, but I think `.node` makes it easier to tell what is going on in your parsed result

And yeah, I think you generally want your Parsimmon parser to succeed. If you examine the parsed result and fail later, you can have more context about your errors, and more importantly, report _multiple_ errors at once.

With parse failures you can only report the very first thing that fails (because presumably it's a failure you can't recover from)

**Comment by wavebeem** [comment]
Have you used `.mark()` or `.node(name)` before? I'm curious if those actually get used much in practice. I think I might want to update the documentation to emphasize how important those functions are.

**Comment by ivan-kleshnin** [comment]
Good explanations, valueable to hear 👍 

> Have you used .mark() or .node(name) before? I'm curious if those actually get used much in practice. I think I might want to update the documentation to emphasize how important those functions are.

No, never. I have to say I have zero prior experience with parsing so I kinda just looked at the examples in 2-3 parsing libraries, found Parsimmon the best documented and having the cleanest API and started to try something for myself. Now I see two examples have `.node()` calls but their results aren't used I guess so I just skipped this information back then.

**Comment by wavebeem** [comment]
Cool, thanks for the info. Should I close the issue now? 🙂

**Comment by ivan-kleshnin** [comment]
👍
