### ISSUE TITLE
Add a guide

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#249]
The API documentation is great, but we need a more comprehensive starter guide, including lots of PROTIPS that people are missing because I have not surfaced them well.

I should definitely add:

* Shorter example of how to parse with nested state (indentation levels, etc)

**Comment by ivan-kleshnin** [comment]
Things I'd like to be covered (among others):

1\. Some performance tips. Which constructions should be considered dangerous performance-wise?

2\. Why there're so few negative constructions out of the box. I can count only `notFollowedBy` and `noneOf`. For example, I find myself lacking something like `P.not`:

```js
let line = P.noneOf("\n\r").atLeast(1).tie().desc("line")
// want something like
let line = P.not(P.end).atLeast(1).tie().desc("line")
```

README features custom `notChar` but I wonder if it's a bad style, or causes a bad performance – that something like this is avoided in core API. Some sort of clarification would be great.

3\. Separator position. Should you try to stick them to the low-level or high-level parser by default.
For example:

```js
let line = P.noneOf("\n\r").atLeast(1).tie().skip(P.end)
// vs
let line = P.noneOf("\n\r").atLeast(1).tie()
// vs
let line = P.noneOf("\n\r").atLeast(1).tie().lookahead(P.end)
```

My experiments suggests that the first version leads to design problems but maybe other people have different opinion.

**Comment by wavebeem** [comment]
1. Agreed, would be a good point to cover. Don't have any interesting things on the top of my head though.

2. You're not the first to ask for a `P.not`... I should definitely dig up why that wasn't added before

3. Ah, yeah, when to parse whitespace is a tricky problem

4. Can you explain more of what you mean here? I'm not following

**Comment by anko** [comment]
> You're not the first to ask for a `P.not`... I should definitely dig up why that wasn't added before

I remember it was thrown around in [this discussion on negative-lookahead](https://github.com/jneen/parsimmon/issues/150#issuecomment-291015531) before.

**Comment by ivan-kleshnin** [comment]
4\. I mean custom parsers that are are more involved

```js
function customParser(???) {
  let state = []
  return Parsimmon(function(input, i) {
    // parse chars
    // do something with state
  })
}
```

@anko what does `._` call do in the following?

```
var forbiddenResult = forbidden._(stream, i)
```

I don't see `_` in the API, only in the examples as a `.optWhitespace` shortcut.

**Comment by wavebeem** [comment]
I've made a PR tracking work on this guide over at https://github.com/jneen/parsimmon/pull/254 so feel free to subscribe to updates on it if you're interested or want to discuss more things you wish you had known when you started using Parsimmon.
