### ISSUE TITLE
Help users become contributors by documenting the internal design of the library

### ISSUE THREAD

**Issue by anko** [jneen/parsimmon#253]
Writing [this comment explaining `._`](https://github.com/jneen/parsimmon/issues/249#issuecomment-394984894) reminded me that it took me a little while to understand Parsimmon's internal design from reading its source.

I think a prose introduction to the internals would help people get started as contributors. Perhaps a `src/readme.md`?

**Comment by wavebeem** [comment]
I definitely agree it took me some time to get the hang of the internals as well, so I can see this being helpful for sure :)

**Comment by wavebeem** [comment]
I think this will be fixed via Parsimmon v2, whenever I get around to that.
