### ISSUE TITLE
New Parsimmon.Binary primitives

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#261]
The root of this bug was "Brian should go to sleep", not anything wrong in Parsimmon. Now the ticket has veered into "feature request" territory. Please scroll down for more 👇 

[link] https://github.com/jneen/parsimmon/issues/261#issuecomment-399949683

~I'm too tired to figure out more right now, but it looks like binary parsers are getting the wrong offset sometimes. In this example the wrong slice of 4 bytes is being passed through to `bitSeq` which is making the whole parser wrong.~

~https://runkit.com/wavebeem/parsimmon-binary-bug~

~The `p.Int32` inside `Int32Array` is seeing `13 37 00 00` as its byte chunk rather than `00 00 00 02` which seems wrong because it should be offset due to `P.seq(B.byte(...), B.byte(...))` ahead of it.~

~cc @theqabalist~

~Since binary parsing was the feature you championed I wanted to ask you if you wanted to take a look, and if you had seen this in your own use of the new `Parsimmon.Binary` module.~

**Comment by theqabalist** [comment]
At first glance, it seems like everything is right because the parser you are using at the top level is
```let ast = Lang.Int32Array.tryParse(input);```

So the first 4 bytes are 13 37 00 00.

Am I misunderstanding something here?  It seems like to get the behavior you want you would need to do something like `Lang.File.tryParse(input)`.

Also, I just want to point out that I do not use bitSeq the way you have used it.  It could be used that way but it's going be slower and more painful than establishing a few other higher level primitives for integer reading.  These are some real parsers I implemented for my binary stuff:

```javascript
const Parsimmon = require('parsimmon');

const intBE = n => new Parsimmon((input, i) => {
    if (i + n > input.length) {
        return Parsimmon.makeFailure(i, `${n} bytes for intBE`);
    }
    return Parsimmon.makeSuccess(i + n, input.readIntBE(i, n));
});
```

```javascript
const Parsimmon = require('parsimmon');

const uintBE = n => new Parsimmon((input, i) => {
    if (i + n > input.length) {
        return Parsimmon.makeFailure(i, `${n} bytes for uintBE`);
    }
    return Parsimmon.makeSuccess(i + n, input.readUIntBE(i, n));
});
```

bitSeq is necessarily both unsigned and big endian.  So it seems like we may want to flesh out the binary package with the 4 primitives I am using under the names uintLE, intLE, uintBE, and intBE.

**Comment by wavebeem** [comment]
Oh wow I should've known I was making a tiny little goof somewhere else. That makes so much sense now, thanks for catching it.

Also that makes a lot more sense. I don't have a lot of experience with buffer and didn't think of these read helpers.

Do you think Parsimmon should have `Parsimmon.Binary.{intBE, uintBE, intLE, uintLE}`? and/or maybe the 8/16/32. Also there's {floatLE, floatBE, doubleLE, doubleBE}.

It would be an awful lot of primitives but it seems probably like something Parsimmon should handle for the user? Otherwise you have to do a lot of boilerplate as shown in your example

**Comment by theqabalist** [comment]
I do all the number manipulation primitives would be useful.  I'm not sure specifically that providing the word length is as useful, though I suppose it just depends on if Parsimmon is the minimalist type or the Ruby friendly interface type.  Either way, I'd be happy to add primitives.  Should I do a PR for them  I think it may be worth having one extra primitive as well.  It's common for strings to be encoded in binary as well, so we could also have a Parsimmon.Binary.string or Parsimmon.Binary.encoded which has the type `(encoding, length) -> Parser Buffer` which will read `length` bytes and decode them using `encoding`.  This is a superficial shim on top of buffer functionality that you can achieve in a map function, but I think it's more helpful than superfluous.  I think it helps people realize what and how they can do things through interface discovery.

**Comment by theqabalist** [comment]
I think so, because the distinction is important, if they only use one then I think they can alias it like you are pointing out.

**Comment by wavebeem** [comment]
Looks like I forgot to close this issue too per https://github.com/jneen/parsimmon/pull/264
