### ISSUE TITLE
Combinator for validation.

### ISSUE THREAD

**Issue by bddap** [jneen/parsimmon#265]
I propose a new combinator, `assert`, which validates a previously yielded value.

Example use case, parse an ipv4 address:

```js
const octet = P.digits.map(Number).assert(n => n < 256, "too large")
const ipv4 = octet.sepBy(P.string('.')).assert(octets => octets.length === 4)
console.log(ipv4.parse("1.2.3.4").value) // [1, 2, 3, 4]
console.log(ipv4.parse("1.300.3.4").status) // false
```

Pull request incoming.

**Comment by wavebeem** [comment]
honestly this method is what i would expect `test` to be if it weren't already a single character parser :)

**Comment by zicvic** [comment]
This would very much be appreciated :)

**Comment by wavebeem** [comment]
Closing this as the OP closed the corresponding pull request, in order to clear up the issue tracker.
