### ISSUE TITLE
Error formatting versatility.

### ISSUE THREAD

**Issue by theqabalist** [jneen/parsimmon#271]
I don't know that I quite know where to go with this, so I am just going to throw it out there to start the discussion.  Since we improved our error formatting, we seem to have forgotten about situations where multi-line errors are a burden, such as in api calls, etc.

Is this something we expect the library consumer to reformat?  Because then we are leaking the implementation of the parse object to consumers, thereby locking it down.  I don't know if that's in the original contract.  Should we potentially come up with a pretty-error and compact-error or something similar?

**Comment by wavebeem** [comment]
The way I see it, the formatted errors are a convenience. Our logic is not
privileged within Parsimmon and could be reimplemented by an outside
consumer for other formats. The original use case seems to be manually
passing the input string and the .parse failure result to .formatError, but
really the API consumer could use the error result themselves.

**Comment by theqabalist** [comment]
I considered that, but are you ok locking down the error result format? Or is it already contractually bound?

**Comment by wavebeem** [comment]
That's a fair point. The errors for each parser are not specified right now
as part of the API except maybe by coincidence in some of the tests, if I
remember correctly.

**Comment by wavebeem** [comment]
I'm not really against making the error results better documented and covered in the testing, but I don't know how much work it will be and don't feel like looking into it at the moment.

Has this been a problem for you so far?

**Comment by theqabalist** [comment]
Only minorly.  Given that I currently contribute to this project, I am not opposed necessarily to implementing my own error formatter against the internal representation, as I feel like I am more privy than other people to the changes it may undergo.  I just didn't know what direction the library as a whole wanted to take.

The issues I have had with it thus far is that I can't return an easy to read error from an API while developing.  I'm not sure that I would necessarily even return the parser error on something like 400 because it's not quite the level of detail you would want for a user facing error anyway.  So it's not a major thing for me, just something I was considering.

**Comment by wavebeem** [comment]
It could make sense to also have a terse error message function inside
Parsimmon, similar to the old form, formatTerseError or formatErrorShort or
something
