### ISSUE TITLE
How to parser the multiline block lexer with multi token start or end

### ISSUE THREAD

**Issue by lichenhao** [jneen/parsimmon#272]
Ok, the code is here and it has some problems, but I don't known why this can not go through

```javascript
import P from 'parsimmon'
const Parser = P.createLanguage(
  Comment: r => P.string('/*').chain(t => {
    const end = '*/'
    let body = ''
    return P.takeWhile(s => {
      body += s
      if (body === end) {
        body = s
        return false
      }
      if (body.length > 1) {
        body = s
      }
      return true
    })
  }).skip(P.end).desc('Comment')
})

//// out 
console.log(Parser.Comment.tryParser(`/*abc*/`)) // -> throw errors 
```

**Comment by wavebeem** [comment]
The problem I see is you're checking `body === end` which means `body === "*/"`, but you're also doing `body += s`. I think you meant to check `s === end` instead?

Also, `takeWhile` gets passed only one character at a time, so `s === "*/"` could never be true.

I think parsing a C-style comment works best with a regexp:

```js
P.regexp(/\/\*(.*)\*\//)
```

**Comment by lichenhao** [comment]
Yeap ! ~  It works well. 
Thank you.
