### ISSUE TITLE
Odd behavioral intersection of combinators (alt/or and times).

### ISSUE THREAD

**Issue by theqabalist** [jneen/parsimmon#273]
I am experiencing behavior which I both don't expect, and do not immediately understand.  It seems like however times is implemented breaks the usage of the fallback combinators.  Both alt and `.or` seem to break when used with times.  Example:

```javascript
const P = require('parsimmon');

P.digit.times(2).or(P.any.atLeast(1).tie()).tryParse('56a') // throws exception because the first parser fails.

P.alt(
  P.digit.times(2),
  P.any.atLeast(1).tie()
).tryParse('56a') // also fails
```

This would seem to be incorrect behavior.  I can work on a fix if anyone can corroborate that this is not supposed to behave this way.

**Comment by wavebeem** [comment]
I think this one came up before. The problem is that `P.alt` succeeds, but `tryParse` ultimately fails because after the alt succeeds there is a remaining `"a"` as input, and thus you failed to parse the entire input.

**Comment by wavebeem** [comment]
This isn't a bug but it is confusing. Definitely curious how we could make the error messaging more obvious here. What is being show in the console exactly?

**Comment by theqabalist** [comment]
```
> P.digit.times(1).or(P.any.atLeast(1).tie()).tryParse('56a')
Error:
-- PARSING FAILED --------------------------------------------------

> 1 | 56a
    |  ^
Expected:

EOF
```

I think I understand what you are saying.  The alt is being terminated by the successful sub parse and the we are hitting EOF?

**Comment by wavebeem** [comment]
Exactly. I think the main thing we could do to mitigate this is add in some helpers for tracing the flow of parsing. To be honest I haven't really given much thought to it recently, but there should be an open issue if you wanna discuss there.

**Comment by theqabalist** [comment]
I did check the issues first.  I don't see one that at least, by title, reflects this issue.  Is it not possible to structure a parser that "parses a number of digits, or falls back to a string"?

**Comment by theqabalist** [comment]
I suppose I could always parse a string and try to promote to a number.

**Comment by theqabalist** [comment]
oh wait, if I make the EOF explicit, then it would actually fail.  So something like `seq(digits, EOF)` would fail in the alt.

**Comment by theqabalist** [comment]
I agree with you on not being sure how to properly back track for meaningful error reporting.  I will think on it some.

**Comment by wavebeem** [comment]
Based on https://github.com/jneen/parsimmon/issues/143 I'm likely to go ahead and implement https://github.com/jneen/parsimmon/issues/193 (which you could monkey patch locally and play with)
