### ISSUE TITLE
Parsimmon blog post

### ISSUE THREAD

**Issue by MaxGabriel** [jneen/parsimmon#274]
With apologies for abusing the issue tracker: I thought watchers of this repo might like this blog post I just wrote about Parsimmon https://medium.com/mercury-bank/a-magic-date-input-using-parser-combinators-in-typescript-3c779741bf4c. Thanks for writing and maintaining this library 👍

**Comment by wavebeem** [comment]
Not a problem at all to use the issue tracker for this.

This blog post looks fantastic from my initial skim. Would you mind if I linked to it in the README?

**Comment by MaxGabriel** [comment]
Sure, go ahead!
