### ISSUE TITLE
Learning parsimmon need some advice

### ISSUE THREAD

**Issue by LeapInSoft** [jneen/parsimmon#275]
Hello,
I try to learn Parsimmon, first time I try to use Parsing combinator I'm litle bit lost.
I try to parse line with some data to convert into array, I don't want to use `seqBy` because it can succeed without ':' too 
```
let value = P.regexp(/[0-9A-Za-z\-\_]+/)
let arrayValue = P.alt(
                    P.seq(value, P.string(':')).map(x => x[0]),
                    value
)
let array = arrayValue.many()
let line = P.alt(
        P.seq(array, P.string("\n")).map(x => x[0]),
        array
)
let lines = line.many()
lines.tryParse("friends:100:3d4:Same\nfriends:100:3d4:Same")
```

In this case I have  _infinite loop detected in .many() parser --- calling .many() on a parser which can accept zero characters is usually the cause_
But my parser work with `let lines = line.times(2)` I don't know how handle multi line.

**Comment by wavebeem** [comment]
I'm not sure what's wrong with the code at a glance, but have you tried using `sepBy1`? I think it will accomplish what you need a lot easier than the approach you're taking right now.

**Comment by LeapInSoft** [comment]
I have a try with `seqBy1`but splitting for convert to array is the not the main problem for me, but how parse line by line. Sorry if this is obvious but I try to learn.
How do you parse my sample `friends:100:3d4:Same\nfriends:100:3d4:Same` ?

**Comment by wavebeem** [comment]
```js
let P = require("parsimmon");
let value = P.regexp(/[0-9A-Za-z\-\_]+/);
let line = value.sepBy1(P.string(":"));
let lines = line.sepBy1(P.string("\n"));
lines.parse("a:100:c\nx:x:y:z:90:x5");
```

This should do the trick

**Comment by wavebeem** [comment]
Ah, I see. The problem is you should've been using `atLeast(1)`. Before, `array` could be empty, and then `lines` was many of `array`, so it would keep parsing empty string repeatedly 😄

**Comment by LeapInSoft** [comment]
Thank you for your help :)

**Comment by wavebeem** [comment]
In general . many is pretty dangerous! Happy to help
