### ISSUE TITLE
Parsing everything that doesn't match

### ISSUE THREAD

**Issue by vangberg** [jneen/parsimmon#276]
Hi! I have been wrestling with this for some time, and I hope it is okay to ask a question here.

Among other things I want to parse references in the form of `[[123]]` in otherwise plain text. So, for this input:
```
Here is a reference: [[123]]
And this [[9]] is another.
``` 
I am looking for this result:
```
[
  { type: "text", value: "Here is a reference: " },
  { type: "reference", value: "123" },
  { type: "text", value: "And this " },
  { type: "reference", value: "9" },
  { type: "text", value: "is another." }
]
```

I mostly achieve this with the following code:
```javascript
import P from 'parsimmon'

const reference =
    P.string("[[")
        .then(P.digit.many())
        .skip(P.string("]]"))
        .tie()
        .map(result => ({ type: 'reference', value: result }))

const other =
    P.any
        .map(result => ({ type: 'text', value: result }))

const parser =
    P.alt(reference, other)
        .atLeast(1)

export const parse = (input) => parser.parse("Here is a reference: [[123]]\nAnd this [[9]] is another.")
```
But since the `other`-parser only matches 1 characted at the time, I end up with a `{ type: "text", result: ... }` for each single character. I have not been able to work my way around this with a different parsing strategy, so instead i map the final result with the following function, which merges adjacent text-results:
```javascript
const collapseTexts = result => {
    return result.reduce((accumulator, current) => {
        const previous = accumulator[accumulator.length - 1]

        if (previous && previous.type === 'text' && current.type === 'text') {
            const head = accumulator.slice(0, accumulator.length - 1)
            const next = { type: 'text', value: previous.value + current.value }
            return head.concat([next])
        }

        return accumulator.concat([ current ])
    }, [])
}

const parser =
    P.alt(reference, other)
        .atLeast(1)
        .map(collapseTexts)
```
Which is okay, but I would like to know if there is a better way to do this.

Best regards!

**Comment by vangberg** [comment]
After spending all day trying to solve this, I obviously solve it 10 minutes after posting an issue. I found the answer in https://github.com/jneen/parsimmon/issues/203#issuecomment-332371099

Changing `other` to the following works:

```javascript
const other =
    P.notFollowedBy(reference)
        .then(P.any)
        .atLeast(1)
        .tie()
        .map(result => ({ type: 'text', value: result }))
```

**Comment by jneen** [comment]
I should mention that this problem is likely better solved with a regular expression, unless your syntax has nesting of some kind in it. Parsimmon is likely to be slow, since it has to use a js loop to check every case.
