### ISSUE TITLE
What's the best way to parse a quoted string literal?

### ISSUE THREAD

**Issue by tom-sherman** [jneen/parsimmon#277]
I want to be able to parse strings in the form of JS string literals.

Eg.

```
"he\"llo"
"\\hello"
'hello'
'he"llo'
```

Is this possible with this library? Or do I have to write a custom parser?

Using [this SO answer](https://stackoverflow.com/questions/24106314/parser-for-quoted-string-using-parsec) I've managed to get to close, but it's not quite working as expected:

```js
// all the characters which can be escaped
const Escape = P.string('\\')
  .then(P.oneOf('\\"0nrvtbf'))

const NonEscape = P.noneOf('\\\"\0\n\r\v\t\b\f')

const Character = NonEscape.or(Escape)

const Quote = P.alt(P.string('"'), P.string("'"))

const Str = Character.many()
  .wrap(Quote, Quote)
  .map(result => result.join(''))
```

**Edit: I think I have it working for just double quoted strings**

```js
// all the characters which can be escaped
const Escape = P.string('\\')
  .then(P.oneOf('\\"\''))

const NonEscape = P.noneOf('\\\"\0\n\r\v\t\b\f')

const Character = NonEscape.or(Escape)

const Str = Character.many()
  .wrap(P.string('"'), P.string('"'))
  .map(result => result.join(''))
```

**Comment by wavebeem** [comment]
You can also check out the JSON example parser

https://github.com/jneen/parsimmon/blob/master/examples/json.js

**Comment by tom-sherman** [comment]
Thanks for the pointer!
