### ISSUE TITLE
Specify supported node version in package.json

### ISSUE THREAD

**Issue by golopot** [jneen/parsimmon#280]
Supported node version can be specified in package.json as
```jsonc
{
  "engines": {
    "node": ">=6"
  }
}
```
Packages depending on parsimmon cannot claim they support node 6 if parsimmon does not officially support node 6.

**Comment by anko** [comment]
I think we might not need this. CI test results are publicly accessible at https://travis-ci.org/jneen/parsimmon, and Node 6 passes. An `engines` field is a much lesser guarantee than that.

**Comment by wavebeem** [comment]
This is true, though I had to disable node6/7 CI because they won't run Karma or Webpack correctly now :(
