### ISSUE TITLE
Standalone browser version does not start without Buffer polyfill

### ISSUE THREAD

**Issue by makoven** [jneen/parsimmon#282]
This error appears in the broser console:

> Error: Buffer global does not exist; please consider using https://github.com/feross/buffer if you are running Parsimmon in a browser.

Works well after adding:

> window.Buffer = { isBuffer: () => false };

(Without `isBuffer: () => false ` throws on parse error)

**Comment by wavebeem** [comment]
Thanks for bringing this to my attention. I'll try to fix it when I get
some time.

**Comment by wavebeem** [comment]
Version 1.12.1 was just published and fixes the issue, as well as adding headless Chrome tests to ensure this won't break again. Thank you for the bug report.

https://unpkg.com/parsimmon@1.12.1/build/parsimmon.umd.min.js

**Comment by makoven** [comment]
It works now. Thank

**Comment by bd82** [comment]
Great I think I will now be able to update the version used in the benchmark 😄
