### ISSUE TITLE
Suggestion: parser.failIf(cond, message)

### ISSUE THREAD

**Issue by minamorl** [jneen/parsimmon#285]
I wish there are kind of this.

```ts
parser.failIf(v => someExpression, "error message")
```
It is a shorthand of this:

```ts
parser.chain(v => condition(v) ? P.fail(message) : P.succeed(v))
```
Isn't it reasonable?

**Comment by wavebeem** [comment]
Can you share some example code? I'm curious how you would use this.

**Comment by minamorl** [comment]
Sure. The real working example is messy so below is the only key point from my markdown parser code. 

For example, it can be useful with `Parsimmon.alt`. 

```ts
const listParser = P.seqMap(P.index, P.string("- "), P.regex(...))
  .map(([index, _1, value]) => ({index, value}))
  // Markdown list should be started from multiple of 2 spaces
  .failIf(v => v.index.column % 2 !== 0, "indentation error")
  .map(...);
// listParser cannot use P.string("  ").many() for this
const parserThatConsumesSpace = P.regexp(/\s+/).result("");

const parsers = P.alt(parserThatConsumesSpace, listParser, fallbackParser).many()
```
As you can see, you can enforce the parser to be fail and pass to the next parser as a fallback, on any condition.

**Comment by wavebeem** [comment]
How about the opposite, `.assert`?

```js
const listParser = P.seq(P.index, P.string("- "), P.regex(...))
  .map(([index, _1, value]) => ({index, value}))
  // Markdown list should be started from multiple of 2 spaces
  .assert(v => v.index.column % 2 === 0, "indentation error")
  .map(...);
```

**Comment by minamorl** [comment]
Looks good to me. I respect your design 👍

**Comment by wavebeem** [comment]
Do you want to make a PR? Otherwise it might take me a while.

**Comment by minamorl** [comment]
I'll make a PR. Give me a sec.

**Comment by wavebeem** [comment]
Thanks! I appreciate it.

**Comment by minamorl** [comment]
I sent a PR. I can't write a grammatically correct documentation, so review my PR and after that plz add a note on API page :sparkles:

**Comment by wavebeem** [comment]
ありがとう！ I will add documentation and release it soon.

**Comment by wavebeem** [comment]
Version 1.13.0 released!
