### ISSUE TITLE
Question: saving consumed input?

### ISSUE THREAD

**Issue by nscarcella** [jneen/parsimmon#289]
Hi, I'm using the library to implement a parser that outputs an AST and I would like to save the source code that generated certain nodes, but I would rather not iterate the whole AST inserting the matching text if I could avoid it.

The grammar is not regular and I have no easy way to reconvert the nodes to strings so I thought I could make it work by using lookAhead but, sadly, I couldn't find a clean way to obtain the input that lookAhead processed, since it's not really consumed.

I ended up doing this:

```typescript
myParser.thru(originalParser => {
          let sourceSize: number
          let source: string

          const lookAheadSourceSize = lookahead(
            originalParser
              .mark()
              .map(({ start, end }) => { sourceSize = end.offset - start.offset })
          )

          const lookAheadSource = lookahead(
            any
              .times(sourceSize)
              .tie()
              .map(r => { source = r })
          )

          return lookAheadSourceSize
            .chain(_ => lookAheadSource)
            .then(originalParser)
            .map(r => ({ ...r, source }))
        })
```

It works, but it feels unnecessarily complex and dirty.

Do you think there is an easier way to convert a Parser<T> into a Parser<T & {source: string}> without revisiting the input after the parser? Or perhaps there is a way to retrieve the input the lookAhead has processed?

**Comment by wavebeem** [comment]
No need for lookahead at all, .chain and a custom parser are all you need:

https://runkit.com/wavebeem/parsimmon-issue-289

Run that and dig into the result object and you can see it captures the text necessary.

I considered adding the source text along with the start/end info but decided against it since you can find it yourself by using `input.slice(start.offset, end.offset)`.

**Comment by nscarcella** [comment]
Nice. I didn't realize custom parsers had access to the whole input, not just what is left.

This completely solves my usecase.

Thanks a lot.
