### ISSUE TITLE
Feature for separated sequences?

### ISSUE THREAD

**Issue by Bartvds** [jneen/parsimmon#29]
I've used parsimmon for a bunch of projects and it works very nice, but I miss a build-in feature for separated lists.

It is easy to rig using `many()`, `skip()` and `map()`, but a general (optimal) solution could be nice.

Something like `Parsimmon.sep(words, space)` that would return an array of words with spaces.

I just throw it out there, see what you think.

**Comment by hughfdjackson** [comment]
@jneen Might want to close this issue :D

**Comment by jneen** [comment]
ah yes, thanks!
