### ISSUE TITLE
Question: scanning for matches

### ISSUE THREAD

**Issue by ahamid** [jneen/parsimmon#293]
I have some regex-based code that scans for various patterns and am testing conversion to parsimmon.  I infer that `sepBy` is the idiom to use, and this kind of works:
```javascript
const ScanDigits = P.digits.sepBy(P.any)
console.log(ScanDigits.parse('any 123 thing 456 but 789 digits'))
```
```javascript
{ status: true, value: [ '', '123', '456', '789', '' ] }
```
(update: interestingly, if I change `P.digits` to a regex that matches at least one char, as described by #166, this parse fails)

But if I try a more complicated example, I run into problems:
```javascript
const DigitsPrefixed = P.seqMap(P.string('='), P.digits.node('Digits'), (__, node) => node)
const ScanDigitsPrefixed = DigitsPrefixed.sepBy(P.any)
console.log(ScanDigitsPrefixed.parse('any =123 thing =456 but =879 digits'))
```
```javascript
{
  status: false,
  index: { offset: 0, line: 1, column: 1 },
  expected: [ "'='", 'EOF' ]
}
```

I have tried several variations including using `trim`, `notFollowedBy(DigitsPrefixed)` and alternating with `P.eof`.
Is there a way to achieve this (perhaps there is a way to iteratively parse?).

TIA for any insight.

**Comment by wavebeem** [comment]
I would treat the non-digit text as "whitespace" that comes before and/or after your target characters, then use .many() to parse it.

I think the main issue comes from using `P.any` which is matching more than what you want. Notice that I specifically called out the opposite list of characters in this example:

```js
const NotDigits = P.regexp(/[^0-9=]*/);
```

https://runkit.com/wavebeem/jneen-parsimmon-issues-293

**Comment by wavebeem** [comment]
I'm going to close this issue, but feel free to comment if you have more questions or think you've found a bug.

**Comment by ahamid** [comment]
Thanks @wavebeem.  When I try that example, an input of `'an=y =123 thing1= =456 but =879 digits'` will yield `expected: ["/[0-9]+/"] index: Object {column: 4, line: 1, offset: 3}`, however I can construct a custom general purpose `not` function to consume any leading and trailing characters that _don't_ parse with the target parser:

https://runkit.com/ahamid/5e407872e00e8e0014dcc97c

**Comment by wavebeem** [comment]
You might also be interested in using `notFollowedBy` https://github.com/jneen/parsimmon/blob/master/API.md#parsernotfollowedbyanotherparser
