### ISSUE TITLE
Multiple error reporting (error recovery)

### ISSUE THREAD

**Issue by phuongduyphan** [jneen/parsimmon#294]
Is there any way for the parser to recover from errors, continue parsing to the end of the input and report multiple parsing errors? 

Currently, the parser stops parsing when it encounters the first error.

**Comment by wavebeem** [comment]
I'm not really sure a good way to do that sort of thing automatically, but you can do it yourself by using `.alt()` or `.or()` and reading in extra characters.

```js
const FunctionCall = P.alt(
  Var.skip(P.string("()")),
  P.regexp(/[^;]+/).node("SyntaxError")
);
```

**Full example:**

<https://runkit.com/wavebeem/parsimmon-issues-294>

Basically you need to identify which pieces of the parser can fail and make some kind of "failure" node for them.

**Comment by anko** [comment]
In other words, make your parser *also match wrong inputs* and return them as successes, but with data representing the way in which the input was wrong.  Then handle those "successful errors" at the top level of your parser.

**Comment by wavebeem** [comment]
@anko yup! i think "catching" these parse errors at the Statement level makes sense for a statement driven language, probably. but if you wanted something even more advanced, like an autocomplete engine for partially written code, you'd probably have to get even more data down to the expression level.

@phuongduyphan i hope this helps! if not, please leave a comment and i can re-open the issue.
