### ISSUE TITLE
It seems that or/alt won't work on fail

### ISSUE THREAD

**Issue by Shuumatsu** [jneen/parsimmon#295]
I tried this `console.log(alt(fail('this always fails'), of("succ")).tryParse('...'))`

I think the expected result will be `"succ"`, but I got this: 

```
    Expected one of the following:

    EOF, this always fails
```

Is this designed behavior or not? If I want this to work, what should I do?

**Comment by wavebeem** [comment]
Hi there! This behavior is correct. You must consume the entire input string when calling `.parse` or `.tryParse`! `of` does not consume any input, so the entire string `"..."` is left over afterwards, so `.tryParse` fails. You can use `P.all` if you want to consume the rest of the input:

https://runkit.com/wavebeem/parsimmon-issues-295

I will see if I can improve the error message for this use case.

**Comment by wavebeem** [comment]
I'm looking at this program:

```js
var P = require("./src/parsimmon.js");

console.log(P.of("blah").parse("hello world"));
console.log();
console.log("####################################");
console.log();
P.of("blah").tryParse("hello world");
```

Which outputs:

```
{
  status: false,
  index: { offset: 0, line: 1, column: 1 },
  expected: [ 'EOF' ]
}

####################################

D:\w\parsimmon\src\parsimmon.js:848
    throw err;
    ^

Error:
-- PARSING FAILED --------------------------------------------------

> 1 | hello world
    | ^

Expected:

EOF

    at Parsimmon._.tryParse (D:\w\parsimmon\src\parsimmon.js:845:15)
    at Object.<anonymous> (D:\w\parsimmon\example.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)
    at internal/main/run_main_module.js:17:11
```

Is there a different message you would expect here? Maybe I should say "`.parse` parses the ENTIRE string input, and will error if there is any leftover characters" in API.md?

**Comment by Shuumatsu** [comment]
I forgot how parser combinators work and I wrongly thought `of` will always result in the accept state under all conditions...

---

In fact the error message 

```
Expected:

EOF
```

I think sometimes `Expected` is not very helpful. I may write something like this for more details about what's happening.
```
const indent_same = count_spaces.chain(n => (n == indent ? of(n) : fail(`${indent} spaces (but got ${n})`)))
```

Maybe instead of just showing the next expected char, showing some more related "env information" may be more helpful.

**Comment by wavebeem** [comment]
Formatted errors include a full source code snippet with line/column pointer too... That's really everything we can show. Unless I'm forgetting something.
