### ISSUE TITLE
Regex dotAll support (/s flag)

### ISSUE THREAD

**Issue by wertlex** [jneen/parsimmon#300]
Hey!

Recently I was playing with Parsimmon and parser combinators, and found quite a nice thing: ECMA2018's `/s` regex flag. 
Some details: 
 - TC-39 proposal: https://github.com/tc39/proposal-regexp-dotall-flag
 - browser support: https://caniuse.com/#search=dotall
 - node support: https://node.green/#ES2018-features--s--dotAll--flag-for-regular-expressions
 - brief introduction: https://2ality.com/2017/07/regexp-dotall-flag.html

Implementation of this feature would be quite a simple thing, but I face some troubles:
 1. which versions of node/browsers library is aimed to support? I see that most of tests are written in "compatible" mode without using modern `const`, `let` and another perks, which allows library to fit wide range of JS versions. Implementing this feature shouldn't bring any problems to the library, but could break tests in node < 8.x (though probably few `try-catches` in tests could do the deal).
 2. there are some problems with `/s` flag recognition by `eslint` I wasn't able to resolve quickly. Probably used `eslint` is slightly outdated, and simply should be promoted from current 4.x to lates 7.x

Anyway, I've made a PR in my local fork: https://github.com/wertlex/parsimmon/pull/1

Let me know if such a support interested for anybody and should I continue with those two points above?

P.S. yeah, `/s` behavior could be quite easily mocked by replacing `.` with `[\s\S]`, but `/s` turns to be more correct way of doing this.

P.P.S on the other hand there is no tests for `imu` regex flags, so probably there is no need test for `s` flag too?

**Comment by wavebeem** [comment]
From the README:

>Parsimmon supports IE7 and newer browsers, along with Node.js

Parsimmon has very wide support. Whenever I feel like working on Parsimmon v2 I will probably only target modern JS engines.

>P.P.S on the other hand there is no tests for imu regex flags, so probably there is no need test for s flag too?

If you tried out `s` and it seems to work fine, I think it's good!

>Let me know if such a support interested for anybody and should I continue with those two points above?

RE: 1
I meant to change `.travis.yml` to test `node` and `lts/*` versions so we don't get left behind as Node keeps getting upgraded. IE7 support means we only get ES3 (!) for Parsimmon.

RE: 2
If we just skip testing for regexp literals using `s` I think this won't be a problem.

Please target this PR at this repo. This feature sounds great.

Thanks for your code and well-explained issue report!

**Comment by wertlex** [comment]
Here we are: https://github.com/jneen/parsimmon/pull/301
