### ISSUE TITLE
MS Edge 18 error

### ISSUE THREAD

**Issue by ekilah** [jneen/parsimmon#303]
```
Error unsupported regexp flag "n": /[0-9]/undefined 
    node_modules/parsimmon/build/parsimmon.umd.min.js:1:6716 Anonymous function
    node_modules/parsimmon/build/parsimmon.umd.min.js:1:6560 K
    node_modules/parsimmon/build/parsimmon.umd.min.js:1:11055 Anonymous function
    node_modules/parsimmon/build/parsimmon.umd.min.js:1:348 r
    node_modules/parsimmon/build/parsimmon.umd.min.js:1:407 Anonymous function
    node_modules/parsimmon/build/parsimmon.umd.min.js:1:199 Anonymous function
    node_modules/parsimmon/build/parsimmon.umd.min.js:1 Anonymous function
    webpack/bootstrap:25:3 __webpack_require__
    https://mywebsite.com/static/js/main.abc.js:1:123 Anonymous function
    webpack/bootstrap:25:3 __webpack_require__
```

Seeing the above a few times in my error tracker for Windows 10 devices running Edge 16 and Edge 18 (very old, non-chromium builds of the Edge browser).

Running the latest `parsimmon` at `1.15.0`. We just recently upgraded from `1.12.0` and I hadn't noticed these errors previously, if that's helpful.

The error message is a bit odd, but my guess is that `RegExp` on these versions of Edge don't support flags very well. It looks to me after reading the source for `parsimmon` that the regexp is literally presenting as the string `"/[0-9]/undefined"` when `flags` converts it to a string:

https://github.com/jneen/parsimmon/blob/cb77d09f900bb292389f0cf4870126bb5aa8b8d9/src/parsimmon.js#L696-L699

I tried to see if I could install that version on my Windows 10 machine, but I guess Microsoft has made that difficult to do side-by-side with the new Edge, so I wasn't able to finish that try. 

I mostly only bring this up because your README claims to support IE7+. I think this case would be not too hard to detect, if you're willing to test it and support these old Edge versions.

**Comment by wavebeem** [comment]
So you're saying `/[0-9]/` turns into `"/[0-9]/undefined"` when it's turned into a string in Edge 18? What a mess, Edge!

The `flags` function is only there because `regexp.flags` doesn't exist in old browsers.

Perhaps this selection of old VMs would be useful to you? https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

Are you interested in contributing a PR to fix this? It seems like you could do a check like `if (re.flags !== undefined) return re.flags` right at the top so we can just use the built-in flag property if it exists.

Maintaining code coverage could probably be done by making a regexp object and then calling `re.flags = undefined` on it to simulate an old regexp from IE.

**Comment by ekilah** [comment]
> So you're saying `/[0-9]/` turns into `"/[0-9]/undefined"` when it's turned into a string in Edge 18?

That's what the Bugsnag error reports suggest, anyway. I am surprised by this as well. I wish I could confirm it, maybe I can with the VM link you suggested.

> The `flags` function is only there because `regexp.flags` doesn't exist in old browsers.

Yeah, I noticed that on the MDN docs/caniuse. Specifically it seems to be missing on.... IE/old Edge. -_-

> Are you interested in contributing a PR to fix this? It seems like you could do a check like `if (re.flags !== undefined) return re.flags` right at the top so we can just use the built-in flag property if it exists.

I would be willing to, but I would feel bad about making a PR for something I can't test. I was hoping maybe you had access to a machine that could prove the theory re: the cause. Again maybe I'll have time to do something with a VM to help out.

After reading the code here I can't see what else could cause it, since your error message prints the regex here:

https://github.com/jneen/parsimmon/blob/cb77d09f900bb292389f0cf4870126bb5aa8b8d9/src/parsimmon.js#L466

-----

My only remaining thought is that I wasn't seeing these errors before I upgraded to the latest version, so I was wondering if you had ideas on any recent behavior changes that could have caused this. I haven't checked whether or not I had users on that browser version before my upgrade to `1.15.0`, but I presume I did, since these errors showed up within an hour or two of the upgrade.

**Comment by wavebeem** [comment]
I'm not really sure what could've broken it. The internal `flags` function in Parsimmon has not changed since v1.12.0. I'm not sure it's been changed since I added it ages ago, in fact.

https://github.com/jneen/parsimmon/blob/v1.12.0/src/parsimmon.js#L664-L667

I downloaded the VM from their site and the oldest I can get is Edge 44 from 2018, which is not capable of reproducing the issue. 

Are you 100% sure your application code hasn't changed? If you somehow did `/[0-9]/ + someVar` and `someVar` was undefined, you would see the result in question (`"/[0-9]/undefined"`).

**Comment by ekilah** [comment]
> Are you 100% sure your application code hasn't changed? If you somehow did `/[0-9]/ + someVar` and `someVar` was undefined, you would see the result in question (`"/[0-9]/undefined"`).

The text in the error message in our bug tracker ("unsupported regexp flag") matches 100% with the string here:
https://github.com/jneen/parsimmon/blob/cb77d09f900bb292389f0cf4870126bb5aa8b8d9/src/parsimmon.js#L466

not to mention the call stack being from the `parsimmon` library, and also `parsimmon` creates this regex:
https://github.com/jneen/parsimmon/blob/cb77d09f900bb292389f0cf4870126bb5aa8b8d9/src/parsimmon.js#L1334

**Comment by ekilah** [comment]
We made a bunch of dependency updates all at once (upgrading webpack and other things), so there aren't any guarantees I can give from my end like "this was all I changed" unfortunately. But we didn't change anything about how we use Parsimmon.

I think testing on Edge 16/18 would be the best next step; if the VMs don't allow it, let me see if my old windows 7 machine gathering dust can install it.

**Comment by ekilah** [comment]
It seems literally impossible to find a way to install this ancient version of Edge, I can't find an installer anywhere... 😬

**Comment by wavebeem** [comment]
> It seems literally impossible to find a way to install this ancient version of Edge, I can't find an installer anywhere... 😬

Yeah this is what I was worried about. For now, I would suggest you fork Parsimmon and try out writing a patch yourself, and deploying it to your own app. Then watch those crash reports and tell me what's up. Additionally, if you could add any kind of logging to Edge about the value of `"" + /[0-9]/` that would be helpful.

If we can get to a high level of confidence about exactly what's happening, I would welcome a patch, but for now I'd like more information.

**Comment by wavebeem** [comment]
Maybe you could even just add some kind of value logging to the internal `flags` function, like call stack and value of the `re` argument or something.

**Comment by ekilah** [comment]
I've put the below results of my testing in a PR (https://github.com/jneen/parsimmon/pull/304). It does seem like the literal string `"undefined"` is rendered to the regex when it is stringified on these old browser versions.
