### ISSUE TITLE
Question: How to parse html comment 

### ISSUE THREAD

**Issue by kucinl** [jneen/parsimmon#307]
Hi，I want to parse something like:
`<!-- this is a comment form comment biz-com -->`
I think i need something like `notFollowedBy` which won't fail, or some thin like [Lexer Modes](https://sap.github.io/chevrotain/docs/features/lexer_modes.html)

**Comment by wavebeem** [comment]
I think a regular expression is best for this parser:

```js
Parsimmon.regexp(/(<!--)(.*?)(-->)/, 2)
```

**Comment by kucinl** [comment]
Thanks. I have another question
If I want parse
`<container attrs>
  <child1>content<child1>
<container>
`
to
`
{
name: 'container',
children: [{name: 'child1'}]
}
`
How to do this? The start tag is the same as end tag without end line like '</' 
It seems `Parsimmon.chain`  can't help

**Comment by anko** [comment]
@kucinl 
You can use `chain` for that.  Parse the opening tag with a parser that outputs the name of the tag, chain into parsing the contents, and an end tag with the same name as the opening tag had.

Illustrative implementation:

```js
let P = require('parsimmon')

let tagName = P.regex(/[a-zA-Z]+/)

// Parser for '<x>', outputting the tag name 'x'
let tagOpener = P.seqMap(
  P.string('<'),
  tagName,
  P.string('>'),
  (opener, name, closer) => name)

// Constructor for parsing '<x>' with a known 'x'
let tagCloser = (name) => P.seq(P.string('<'), P.string(name), P.string('>'))

let text = P.regex(/[^<>]+/)

// A tag can contain other tags, or text
let tagContents = P.lazy(() => P.alt(tag, text).many())

// Parse the opening tag (capturing its name), then contents, and finally a
// closing tag with a matching name.
let tag = tagOpener.chain((name) => {
  return tagContents.map((children) => {
    return { name, children }
  }).skip(tagCloser(name))
})

let parser = tag.many()

let prettyPrint = (obj) => console.log(JSON.stringify(obj, null, 2))

/// Examples

// Fails: no closing tag
prettyPrint(parser.parse('<x>'))

// Succeeds
prettyPrint(parser.parse('<x><x>'))

// Fails: wrong closing tag
prettyPrint(parser.parse('<x><y>'))

// Succeeds
prettyPrint(parser.parse('<x>content1<y>content2<y><x>'))
```

Output:

```json
{
  "status": false,
  "index": {
    "offset": 3,
    "line": 1,
    "column": 4
  },
  "expected": [
    "'<'",
    "/[^<>]+/"
  ]
}
{
  "status": true,
  "value": [
    {
      "name": "x",
      "children": []
    }
  ]
}
{
  "status": false,
  "index": {
    "offset": 6,
    "line": 1,
    "column": 7
  },
  "expected": [
    "'<'",
    "/[^<>]+/"
  ]
}
{
  "status": true,
  "value": [
    {
      "name": "x",
      "children": [
        "content1",
        {
          "name": "y",
          "children": [
            "content2"
          ]
        }
      ]
    }
  ]
}
```

I ignored attributes for simplicity, but you could support them by adding more stuff to the `tagOpener` parser and returning those in the mapper function too.

**Comment by wavebeem** [comment]
Great example, thanks @anko! It would probably be a good idea to have an "XML-ish" example included in the Parsimmon repo
