### ISSUE TITLE
Ignoring XML like tags when encountered inside XML like tags

### ISSUE THREAD

**Issue by william-abboud** [jneen/parsimmon#309]
Good day !

## Preface
I'm creating a language which is a combination of XML like language + markdown.
I've modified the Example https://github.com/jneen/parsimmon/blob/master/examples/xml-ish.js XML-ish language to fit my syntax which is basically XML but not with `<` `>` symbols but with `[` `]` and I am trying to parse the following syntax.

Example:
![image](https://user-images.githubusercontent.com/6226241/101283837-b6de6a00-37e5-11eb-86b9-96d97fe1a3a5.png)

## Problem
The problem I encounter is that I have a markdown code block inside which contains `[i]` and my parser is treating it as a tag and I would like it not to and just consider it as regular content.

I use the following TextContent method

```js
// Text can contain any string without the characters `[` or `]`
  TextContent: () =>
    regex(/[^\[\]]+/).map(text => {
      return {
        type: "text",
        text
      };
    })
```

But unfortunately I can't get my regex to work in order to include the `[i]` as content and not a tag.

![image](https://user-images.githubusercontent.com/6226241/101283933-2f452b00-37e6-11eb-83b0-1b9c8baf30ca.png)

Note: Right now parsing the MD is not a problem.

I appreciate taking your time to look at this, Thank you !

**Comment by wavebeem** [comment]
The standard way to solve this in XML and HTML is to require escaping `<` and `>` within text content. I think you could do a similar thing like `&lbracket;` and `&rbracket;` for example, to escape those characters.

If you need your language to support embedded markdown, I would suggest making a special `[markdown]` tag that doesn't use the normal child logic, but instead is just a regexp just gobbles up everything between matching `[markdown]` and `[/markdown]` tags.

**Comment by william-abboud** [comment]
Thank you for the quick response and suggestion !
