### ISSUE TITLE
Add parser methods wrapTimes, wrapAtLeast, wrapAtMost and wrapMany

### ISSUE THREAD

**Issue by joseDaKing** [jneen/parsimmon#312]
It would  be nice if these parser methods (wrapTimes, wrapAtLeast, wrapAtMost and wrapMany) would be added to the library.

With wrapTimes you can decide exactly how much to wrap.

With wrapAtLeast you can decide minium amount of how much to wrap.

With wrapAtMost you can decide maxium amount of how much to wrap.

With wrapMany you can wrap to infinity or to 0 (wrap not at all).

With optional you can make something optional, this could easily be implemented with using the parser method atMost(1)

I think  personally this features would be helpful, I tried to implement some of them but it was to hard.

**Comment by wavebeem** [comment]
Can you explain how these differ from method chaining?


How does `wrapTimes` compare to the following?

```js
parser.times(n).wrap(before, after)
parser.times(min, max).wrap(before, after)
// --- or ---
parser.wrap(before, after).times(n)
parser.wrap(before, after).times(min, max)
```


Same sort of question for `wrapAtLeast`, `wrapAtMost`, `wrapMany`.

**Comment by joseDaKing** [comment]
This parser will only succeed when the input is "(abra-abra-abra-)"
````js 
string("abra-").times(3).wrap(string("("), string(")"))
```

This parser will only succeed when the input is "(abra)(abra)(abra)"
```js 
string("abra").wrap(string("("), string(")")).times(3)
```

```
```

**Comment by joseDaKing** [comment]
Times followed with wrap will only succeed when the input is "(abra-abra-abra-)"
```js
string("abra-").times(3).wrap(string("("), string(")"))
```

Wrap followed with times will only succeed when the input is "(abra)(abra)(abra)"
```js
string("abra").wrap(string("("), string(")")).times(3)
```

WrapTimes will only succeed when the input is "(((abra)))"
```js
string("abra").wrapTimes(string("("), string(")"), 3)
```

**Comment by wavebeem** [comment]
Parsimmon already has a lot of methods, and I've never wanted this one personally. You can write this in terms of other combinators without a ton of fuss, so I don't want to add 4 new methods.

```js
const P = require('parsimmon');

const x = P.string('x');
const xp = P.string('(').atLeast(1).chain((lp) => {
    return x.skip(P.string(')').times(lp.length));
});

xp.parse('(((x)))');
```

**Comment by joseDaKing** [comment]
To be honest with you I thought I would need it, but I realized now I don't actually need and it is nisch feature. By the way thanks for the answer.

**Comment by wavebeem** [comment]
Ah, good to know. I like hearing real-world use-cases for methods before adding them anyway.
