### ISSUE TITLE
Unneeded code dublication in formatGot

### ISSUE THREAD

**Issue by thephoenixofthevoid** [jneen/parsimmon#313]
This is not a bug in that sense that it doesn't result in a wrong behavior, but I think it's a good thing to fix anyway.

In `function formatGot(input, error)` lines 609-615 and 634-640 are exactly the same.

Permalinks are the following:
https://github.com/jneen/parsimmon/blob/9d87032e070952450f5c89b3d2a9934af94e2961/src/parsimmon.js#L609
https://github.com/jneen/parsimmon/blob/9d87032e070952450f5c89b3d2a9934af94e2961/src/parsimmon.js#L634

Please, let me know if this observation is useful to you, should I report more like this or not?

**Comment by wavebeem** [comment]
Thanks for letting me know. I'm not really concerned about this, or other issues similar to it.

Whenever I get around to Parsimmon v2, I'll be more worried about how idiomatic the code is.

**Comment by thephoenixofthevoid** [comment]
Thanks for a quick reply. I am just making a refactoring of parsimmon's code (I forked it here on github) to a modern javascript, and if I have enough energy, to a typescript as well. I have a unusual use-case that pushes speed requirements to the limit (parsing gigs of data), and I decided to see if I can adopt lib I am used to, for that use-case. I understand that at some point I will have to introduce a way to deal with consequences of having such long strings, but for the first step I am just modernizing the code.

Here is the code: https://github.com/thephoenixofthevoid/parsimmon/blob/master/src/parsimmon.js

Changes are quite aggressive, but they pass given tests, except the following:
1) The binary part of the lib are temporary "disabled"
2) Passing string or RegExp, where parser is expected, will make it into one (like in `.lookahead`)
3) Support for legacy RegExp will be dropped (and disabled in tests)

If you find any of my work useful for v2, let me know here, or by filing an issue in the fork.

**Comment by wavebeem** [comment]
You might be interested in my sister project bread-n-butter (https://github.com/wavebeem/bread-n-butter)

It's all modern TypeScript code, and considerably smaller than Parsimmon. It would probably be an easier starting point for your optimization work.

**Comment by thephoenixofthevoid** [comment]
Wow, thanks. I will check it out.
