### ISSUE TITLE
How do I properly nest then/or/atLeast parsers?

### ISSUE THREAD

**Issue by farcaller** [jneen/parsimmon#314]
I'm working on a Markdown parser implementation using parsimmon, and I'm confused about parser chaining.

I'm trying to write a parser that matches:
- several of
  - either an `Inline` parser unless it starts with `*`
  - or a `Strong` parser

My current attempt at it looked like:

```js
...
.then(notFollowedBy(string('*')).then(r.Inline).or(r.Strong)).atLeast(1)
```

obviously `notFollowedBy`/`then` should be a single parser "unit" there. So I tried

```js
.then(
  seqMap(
    notFollowedBy(string('*')),
    r.Inline,
    (_, i) => i
  )
  .or(r.Strong))
.atLeast(1)
```

which still didn't work.

Any advice how do I properly group the parsers for `atLeast`?

**Comment by wavebeem** [comment]
Hey @farcaller

First of all, I would highly suggest using a pre-existing Markdown parser if at all possible. Markdown is very tricky to parse correctly. https://runkit.com/wavebeem/parsimmon-issues-314

It's a little hard to say what's wrong with the parser based on just this snippet.

I formatted your initial snippet a little bit, and it looks right to me at a glance.

```js
x
  .then(
    notFollowedBy(string("*"))
      .then(r.Inline)
      .or(r.Strong)
  )
  .atLeast(1);
```

**Comment by farcaller** [comment]
I know markdown is tricky to parse but I'm in a situation where I need a PEG-based markdown parser and I'm up for the ~~suffering~~challenge.

Apparently my issue was that I placed `or` outside on the `then`, it's indeed getting tricky to read the code.

FWIW, this is how the parser for my current case ended up looking:

```
function lookbehind(p, ofs) {
  if (ofs === undefined) {
    ofs = -1;
  }
  return Parser((input, i) => {
    const charI = i - ofs;
    if (charI < 0) {
      return makeSuccess(i, '');
    }
    const res = p._(input, charI);
    res.index = i;
    return res;
  });
}

function EmphasisUnderline(r) {
  const lfdr = string('_')
    .notFollowedBy(whitespace)
    .then(alt(
      notFollowedBy(r.PunctuationChar),
      lookahead(r.PunctuationChar).then(lookbehind(alt(whitespace, r.PunctuationChar), 2))
    ));
  
  const lfdrNotRfdr = lfdr
    .then(
      lookbehind(whitespace, 2)
      .or(
        lookbehind(r.PunctuationChar, 2)
        .lookahead(alt(whitespace, eof, r.PunctuationChar))
      )
    );

  const rfdr = string('_')
    .notFollowedBy(lookbehind(whitespace, 2))
    .then(alt(
      notFollowedBy(lookbehind(r.PunctuationChar, 2)),
      lookbehind(r.PunctuationChar, 2).lookahead(alt(whitespace, eof, r.PunctuationChar))
    ));
  
  const rfdrNotLfdr = rfdr
    .then(
      lookahead(alt(whitespace, eof))
      .or(
        lookahead(r.PunctuationChar)
        .then(lookbehind(alt(whitespace, r.PunctuationChar), 2)))
    );
  
  return (
    lfdrNotRfdr
      .then(
        notFollowedBy(rfdrNotLfdr).then(r.Inline).atLeast(1)
      )
      .map(children => ({
        type: 'emphasis',
        children,
      }))
      .skip(rfdrNotLfdr)
  );
}
```

Thanks for your help!

**Comment by wavebeem** [comment]
> Apparently my issue was that I placed or outside on the then, it's indeed getting tricky to read the code.

Aha! I wasn't sure enough to suggest it, but I'm glad that my formatting made that clearer. I love using prettier to autoformat my code, but sometimes those lines can get a little dense, especially with Parsimmon.

Good luck on your Markdown parser! 👍🏻
