### ISSUE TITLE
How can I parse the inside and outside of the parentheses?

### ISSUE THREAD

**Issue by mrsekut** [jneen/parsimmon#315]
I want to determine whether it is inside or outside the parentheses and divide it into the structure of the content as it is, but it does not work.

I find it difficult to determine the end, especially when parsing the outside.

Below are three test cases. (I have defined  "Node" type, but its content is not so important, it is important that it is a data structure that can distinguish inside and outside the parentheses.)

c1 indicates that what is inside the parentheses is not limited to alphabets and numbers.
c2 indicates that whitespace is also left untrimed.
c3 indicates that "(" is considered to be outside if there is no paired ")".

```typescript
export const p = P.createLanguage({
  // root
  parse: r => P.alt(r.inner, r.outside).many(),

  // outside
  outside: () => P.takeWhile(c => c !== '('), // ???

  // inner
  lpran: () => P.string('('),
  rparen: () => P.string(')'),
  inner: r =>
    r.lpran
      .then(P.takeWhile(c => c !== ')'))
      .skip(r.rparen),
});

// types
type Node =
  | { _tag: 'inner'; value: string }
  | { _tag: 'outside'; value: string };

// test cases
const c1Input = '(hoge)is(hoge◆)';
const c1: Node[] = [
  { _tag: 'inner', value: 'hoge' },
  { _tag: 'outside', value: 'is' },
  { _tag: 'inner', value: 'hoge◆' },
];

const c2Input = '( hoge ) is (piyo hoge)';
const c2: Node[] = [
  { _tag: 'inner', value: ' hoge ' },
  { _tag: 'outside', value: ' is ' },
  { _tag: 'inner', value: 'piyo hoge' },
];

const c3Input = '( hoge ) is (piyo (hoge)';
const c3: Node[] = [
  { _tag: 'inner', value: ' hoge ' },
  { _tag: 'outside', value: ' is (piyo ' },
  { _tag: 'inner', value: 'hoge' },
];

// ex.
console.log(p.parse.tryParse(c1Input)); // == c1
console.log(p.parse.tryParse(c2Input)); // == c2
console.log(p.parse.tryParse(c3Input)); // == c3

```

When I run this code, I get an infinite loop detected error due to the ambiguity of the many and outside termination conditions.

**Comment by wavebeem** [comment]
The problem is `inner` and `outer` can parse 0 chars (`""`)

If you wrote `P.string("").many()` you would get the same error

`takeWhile` can parse 0 chars, so it won't work with `many`

```js
const p = P.createLanguage({
  parse: r => P.alt(r.inner, r.outside).many(),
  outside: () => P.regexp(/[^\(]+/),
  lparen: () => P.string('('),
  rparen: () => P.string(')'),
  inner: r =>
    r.lparen
      .then(P.regexp(/[^\)]+/))
      .skip(r.rparen),
});
```

Using `P.regexp` instead with `+` so it parses at least 1 character fixes the problem :)

parsimmonを使うのでありがとうございます！それに、TypeScriptを使うなら、私のbread-n-butterを使うのが好きかもしれません。https://www.npmjs.com/package/bread-n-butter
