### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gyzerok** [jneen/parsimmon#316]
Hello!

First of all let me thank you for your amazing library and willingness to answer questions 🎉 

I am trying to write a parser that looks like this

```ts
type Result = { kind: 'BrackedText', text: string } | { kind: 'Text', text: string }

const result: Result[] = alt(
  seq(string('['), letters, string(']')).map<Result>(...),
  i_dont_know.map<Result>(...)
).many().tryParse(input)
```
And I expect it to parse string `"Hey [hello] how are [world] you?"` into the following
```ts
[
  { kind: 'Text', text: 'hey ' },
  { kind: 'BrackedText', text: 'hello' },
  { kind: 'Text', text: ' how are ' },
  { kind: 'BrackedText', text: 'world' },
  { kind: 'Text', text: ' you?' },
]
```

Basically I want the entire parser to work so, that it parses pieces of string in between `BrackedText` as just strings regardless of what they contain. But I am stuck writing `i_dont_know` parser.

This is a very simplified example. In reality I have several different kind of structures instead of `BrackedText` which I want to parse. So writing parser `takeWhile(x => x !== '[')` wont do the trick.

**Comment by wavebeem** [comment]
Hi! I'm glad you're enjoying Parsimmon. Thank you for the kind words.

https://github.com/jneen/parsimmon/blob/master/API.md#parsimmonnotfollowedbyparser

It's a little hard to say with such a simplified example, but maybe `regexp(/[^\[\]]+/)` or something?

Or perhaps `notFollowedBy` or `lookahead` would be helpful?

**Comment by gyzerok** [comment]
@wavebeem regexp won't to in my case. First of all I am using `parsimmon` to avoid regexes 😄 and I want my last parser basically to parse anything but what my first parser does.

I think you are right and I indeed need something like `notFollowedBy` or `lookahead`, but my problem is that I can't quite figure out how to apply them.

Let me try to rephrase my example a bit: I want to parse specific tokens from string and collect everything in between them as raw string.
```ts
alt(
  p1,
  p2,
  ...,
  pn,
  anything_but_p1_p2_pn,
)
```

Does it sounds clearer to you? Is it possible to parse something like that?

**Comment by wavebeem** [comment]
> First of all I am using parsimmon to avoid regexes

Regexes are good! I think it's hard to use Parsimmon without them. You just need to keep them short :) And you can't build a parser out of just regexes for most languages.

```js
alt(
  p1,
  p2,
  ...,
  pn,
  anything_but_p1_p2_pn,
)
```

This is a good question! Have you tried using `P.any`? That should match a single character. You also have `.many()` after the `alt()`, so it should scan one letter at a time, checking if p1, p2, ... pn matches first, else it gives you back one character. I think that might work.

**Comment by gyzerok** [comment]
> Regexes are good! I think it's hard to use Parsimmon without them. You just need to keep them short :) And you can't build a parser out of just regexes for most languages.

That makes sense yeah

> This is a good question! Have you tried using `P.any`?

Yeah I've tried `any` with `many` with different combinations of `lookahead` and `noFollowedBy` and it usually ends up in the infinite loop error 😅 

Would it be possible for you to show me how what you are talking about would roughly look like? It feels like I am just missing some intuition that should be applied here.

**Comment by wavebeem** [comment]
Something like this should work. Click "Run" to see the results.

https://runkit.com/wavebeem/parsimmon-issues-316

You could make it faster using a custom regexp for `other` that matches more characters at a time, but this is the easiest approach.

**Comment by gyzerok** [comment]
@wavebeem this is amazing! It achieves exactly what I want. Thank you!

Apparently my problem was connected to the fact that I was trying to parse `other` all at once.

I now have a side question through: do I understand correctly that I can apply `atMost` to any and pass it smallest of the previous parser sizes? So instead of parsing 1 letter at a time it will parse several (perhaps it can make overall parsing a bit faster?).

What I min by parser size is minimal amount of characters in a string so this parser can succeed.

If this understanding is correct - is there any way to get the minimal parser size from a parser?

**Comment by wavebeem** [comment]
I think the only way you could make this faster is using a regexp with knowledge of the other parsers.

```js
const P = require("parsimmon");

const round = P.regexp(/[(].*?[)]/).node("round");
const square = P.regexp(/[\[].*?[\]]/).node("square");
const curly = P.regexp(/[{].*?[}]/).node("curly");
const other = P.regexp(/[^{}()\[\]]+/).node("other");

const lang = P.alt(round, square, curly, other).many()

lang.parse("(round) and [square] with {curly}, they all work");
```

This would definitely be faster, but it's more complicated. If my RunKit suggestions is fast enough for you, I would use that.

Cheers!

**Comment by gyzerok** [comment]
@wavebeem I see. In my case previous parsers could be complex and very different. So using regexes to give hints will be kinda problematic.

Probably going through other nodes additionally and collapsing them is a good way forward for me.

Yeah, you library looks very nice. I also love it being TypeScript-native. However it seems to be in experimental shape and not ready for production just yet (as it says in the docs), so I can't go with it for now.

**Comment by wavebeem** [comment]
Yeah, the regexp solution is often difficult, haha.

All I meant was that bread-n-butter is SemVer 0.x, so releases may contain breaking changes. Maybe I will update that text later :)
