### ISSUE TITLE
Question about parsing "define <name> [as <internalName>]" style grammar

### ISSUE THREAD

**Issue by stackunderflow101** [jneen/parsimmon#325]
Hi!

First of all, thank you for authoring such an amazing tool!

I am using parsimmon to parse a custom DSL. Part of the grammar looks like "define {name} [as {internalName}]". For example, "define Javascript" defines an object called "Javascript", while "define Javascript as js" defines such object and also assigns an internal name "js" to it.

What is tricky is that both {name} and {internalName} could contain spaces, like "define pull request as PR", where {name} is "pull request" and {internalName} is PR. In addition, I don't want to put quotes (`'` or `"`) around {name} or {nternalName} to make parsing easier (as it's inconvenient for the end-users). What I want to do is to scan through the input until a stand-alone word "as" appears, and set {name} to be whatever value before "as" (and after "define").

What I have tried is the following parser configuration:

``` js
const internalName = P.string('as')
    .skip(P.whiteSpace)
    .then(P.regexp(/.+/));

export const define = P.seq(
    P.string('define').skip(P.whateSpace),
    P.regexp(/.+/),
    internalName.or(P.of(""))
);
```

It doesn't work. When parsing the string "define pull request as PR", {name} is set to "pull request as PR" instead of "pull request". It's not surprising because parsimmon is greedy. I also took look at functions like `lookAhead` but still could not come up with a solution. We also have a function called `takeWhile` but it doesn't work either. `takeWhile` works only on characters instead of words. Besides, even if I changed the grammar to use `@` instead of `as`, we cannot use `takeWhile` to get all the values before `@`, because there might be words containing `@` (In other words, `@` may not be a standalone word) such as "foo@gmail.com"

Can anyone help me?

**Comment by anko** [comment]
I agree this is tricky.  We want to parse many-words, but stop when we see the word 'as', then parse another many-words.  But the first "many words" greedily matches everything!

I went on a bit of a journey trying this.

My first solution was hacky.  Let it match everything, then use `.map` to process it into the correct format:

```js
const P = require('parsimmon')

const word = P.regex(/\S+/)

const definition = P.string('define').then(P.whitespace)
  .then(word.skip(P.optWhitespace).atLeast(1))
  .map(after => {
    const parts = splitBy(after, 'as')
    const internal = parts[0].join(' ')
    const external = parts[1]?.join(' ') ?? null
    return { internal, external }
  })

function splitBy(array, value) {
  const i = array.indexOf(value)
  if (i === -1) { // not found
    return [array, null]
  } else {
    const left = array.slice(0, i)
    const right = array.slice(i+1)
    return [left, right]
  }
}

console.log(
  definition.parse('define internal name')
)
// => { status: true, value: { internal: 'internal name', external: null } }

console.log(
  definition.parse('define internal name as external name')
)
// => {
//   status: true,
//   value: { internal: 'internal name', external: 'external name' }
// }
```

This "manual parsing" in `.map` sucks though.  The parser is inefficient because it parses more stuff than necessary before detecting an error.  And since the parser isn't handling errors, I'd have had to do error reporting manually, which I realised would be a huge pain.  Parse errors should be handled by the parser.

> We also have a function called `takeWhile` but it doesn't work either. `takeWhile` works only on characters instead of words.

This sounded so much like what the solution *should* be that I was inspired to write that function.  That solution is much neater, excluding the gnarly-as-usual custom combinator definition at the start:

```js
const P = require('parsimmon')

// Define a custom parser combinator that's basically the same as
// `P.takeWhile`, but with each iteration calling a user-given parser, instead
// of stepping character-by-character.
function parseWhile(itemParser, predicate) {
  return P((input, index) => {
    const items = []
    while (true) {
      const itemResult = itemParser._(input, index)
      if (itemResult.status) {
        // Push the item to the results regardless of the predicate result.
        items.push(itemResult.value)
        // Negative predicate; we're done!
        if (!predicate(itemResult.value)) {
          return P.makeSuccess(itemResult.index, items)
        }
        // Otherwise go again, from here.
        index = itemResult.index
      } else {
        // Could not parse item.
        return P.makeFailure(index, itemResult.expected)
      }
    }
  })
}


// The actual parser, using that:

// Note that this is a separate parser now, which can also be used in other
// places, instead of being embedded in a bigger regex.  You can do arbitrarily
// complex parsing here if necessary.
const word = P.regex(/\S+/)

const definition = P.regexp(/define\s+/).then(
  P.alt(

    // Pattern 1: <word>+ 'as' <word>+
    // For example: "define this thing as something else"
    P.seqMap(
      // First parse words up to and including the 'as'
      parseWhile(word.skip(P.optWhitespace), x => x !== 'as')
        // Slice off the 'as'
        .map(x => x.slice(0, -1)),
      // Then parse the rest of the words
      word.sepBy1(P.whitespace),
      // Transform to a neat object
      (internalNameWords, externalNameWords) => {
        return {
          internal: internalNameWords.join(' '),
          external: externalNameWords.join(' ')
        }
      }
    ),

    // Pattern 2: <word>+
    // For example: "define this thing"
    word.sepBy1(P.whitespace).map(internalNameWords => {
      return {
        internal: internalNameWords.join(' '),
        external: null
      }
    })

  )
)


// Testing:

console.log(
  definition.parse('define internal name'))
// => { status: true, value: { internal: 'internal name', external: null } }

console.log(
  definition.parse('define internal name as external name'))
// => {
//  status: true,
//  value: { internal: 'internal name', external: 'external name' }
//}
```

With this, errors are caught early and handled by the parser, and code structure matches grammar structure.  Maybe there is a way of doing this with existing built-ins, but the only ones I could think of always ended up with _some amount_ of the "manual parsing" that the first example was a worst-case of.

Documentation on implementing a custom parser combinator is pretty sparse.  It won't be on the test. :smile:  You're welcome to use this though.

@wavebeem Would `parseWhile` make a good addition to Parsimmon?  I'd already be writing a PR, but maybe I've overlooked an obvious alternative that already exists.

**Comment by stackunderflow101** [comment]
Thank you @anko! I tested this solution locally and it works great for me! I will take some time to see whether I could make the "parseWhile" function better.

For me, I think the best solution to this problem might be to use a lexer and define "as" as a keyword, and we could use "takeWhile" to take all the words before "as". Unfortunately, persimmon doesn't work with a lexer.

**Comment by wavebeem** [comment]
@anko Thanks a bunch for the thorough write-up, I really appreciate the help!

As for putting `parseWhile` into Parsimmon, I'm going to hold off on that. `takeWhile` is insufficient for most cases, I agree, but I think I've let Parsimmon become a bit too large.

Once I can summon the energy, I want to start a `v2` branch based on my work on [bread-n-butter](https://bnb-wavebeem.netlify.app/). When I do this, I'd love to solicit your feedback.

***

@stackunderflow101

If you're thinking of this as a lexer problem, perhaps you'd be better off writing your own recursive descent parser and lexer?

Or would it be enough to say that your "word" parser should include some way of rejecting keywords? I'm not sure what your overall grammar is like, but if you're thinking of this as a lexer problem, that might be sufficient for you.

https://runkit.com/wavebeem/parsimmon-issues-325

You'll have to keep your list of keywords up to date for the `nonkeyword` parser, but this is the solution I would go for, based on what I know about your problem :)

**Comment by stackunderflow101** [comment]
@wavebeem Thank you so much! Yep, this is exactly what I want and it's much simpler!
