### ISSUE TITLE
Is there a way to do something like "everything up until SomeParser"

### ISSUE THREAD

**Issue by trafnar** [jneen/parsimmon#342]
I'm trying to capture all the text up until some pattern. A simplified example of this follows:

Capture the text leading up to the final number, the final number is at the end of the line.

`hello 5` -> captures "hello " and "5"
`hello 2 world 20` -> captures "hello 2 " and "20"

I can write something to capture the last number like "digit followed by end of line" but how can I capture everything up until that match?

I imagine regular expressions that just skip past everything until the last number are an easy way to do this, but I'm wondering if it's possible without that, and using a parser instead, because my actual case is more complicated.

Thank you for any help!

**Comment by wavebeem** [comment]
The only solution I can think of is a parser like this:

1. Read one character
2. Attempt to parse your complicated parser
3. If that parser fails, repeat

You might need to make a custom parser to do this:
https://github.com/jneen/parsimmon/blob/master/API.md#parsimmonfn

**Comment by trafnar** [comment]
That is what I was thinking too (the steps you mentioned), and is the direction I was trying to take, but I couldn't find any way to implement it using the provided parsers.

Thanks for sharing that example, that does seem like the right kind of setup that I would need. I will attempt to build something custom based on that.

I really appreciate your help and all the replies you give in the issues here, even when they aren't "issues" with the library just general questions :) I've been reading through a lot of them and finding tons of helpful code snippets.

**Comment by wavebeem** [comment]
This should work FYI! You don't even need a custom parser. BUT it's limited based on recursion depth of the JS engine.

If you don't need to skip thousands of characters, this is definitely the simplest answer I can think of. My brain isn't capable of conjuring up the right code using `new Parsimmon((input, index) =>` right now, but that would be the way to do it if you want to avoid recursion and also make it faster.

```js
const P = require("parsimmon");

const ab = P.seq(P.string("a"), P.string("b"));

// This has a max skip length based on the max recursion depth of your JS engine...
const eventuallyAB = P.lazy(() => ab.or(P.any.then(eventuallyAB)));

eventuallyAB.parse("x".repeat(999) + "ab");
```

https://runkit.com/wavebeem/parsimmon-skip-until-parser-matches

> I really appreciate your help and all the replies you give in the issues here, even when they aren't "issues" with the library just general questions :) I've been reading through a lot of them and finding tons of helpful code snippets.

Glad it's been helpful! I'm not really active with the library any more, but I'm glad it continues to be helpful.

You might also enjoy my side project, bread-n-butter. It's smaller, has better documentation, and is much easier to write low-level custom parsers for: https://bnb-wavebeem.netlify.app/

**Comment by trafnar** [comment]
Last night I wrote a custom parser called `takeUnless(parser)` which is based on `takeWhile(predicate)`

It yields all characters up until the given parser matches, so in my case its something like:

```javascript
seq(
    takeUnless( MyParser ),
    MyParser,
    OtherStuff
)
```

Going to work on it more today, maybe yield the "taken" content and the result of the parser at the end.
