### ISSUE TITLE
Use all the groups from regex

### ISSUE THREAD

**Issue by barsdeveloper** [jneen/parsimmon#353]
Hello, for an application I'm working on, I'm using Parsimmon to parse text and sometimes the text can be very very long.
For this reason I'm investigating some tricks to increase performance as much as possible and I have found that relying on regex can increase speed considerably.
https://www.measurethat.net/Benchmarks/Show/23438/0/parsimmon-vs-regex
Is there a way, given a regex to retrieve all the groups matched inside it, not just one?
Let's say I want to parse the numbers from a vector therefore I have the following regex: /\(\s*(\d+)\s*,\s*(\d+)\s*\)/, it can parse values like ( 6738, 92882 ) which I would like to map it to {x: 6738, y: 92882}. Is that possible?

**Comment by wavebeem** [comment]
This is not directly supported in Parsimmon, but you could make it yourself.

Start with the `regexp` parser and change it to return the whole match object instead:

https://github.com/jneen/parsimmon/blob/master/src/parsimmon.js#L1212-L1235

**Comment by barsdeveloper** [comment]
And would you accept a pull request in that case?

**Comment by wavebeem** [comment]
Sorry for the late reply. I'm no longer maintaining this repo, so no.
