### ISSUE TITLE
Does parsimmon have a composer?

### ISSUE THREAD

**Issue by bcherny** [jneen/parsimmon#37]
So with parsimmon I can do this (from the readme):

```js
expr.parse('(add (mul 10 (add 3 4)) (add 7 8))').value
// => ['add', ['mul', 10, ['add', 3, 4]], ['add', 7, 8]]
```

How do I perform the opposite operation?

```js
compose(['add', ['mul', 10, ['add', 3, 4]], ['add', 7, 8]])
// => "(add (mul 10 (add 3 4)) (add 7 8))"
```

**Comment by jneen** [comment]
It doesn't.  You generally have to write pretty-printers yourself.

**Comment by jneen** [comment]
usually it's a pretty simple traversal over the data structure, though

**Comment by bcherny** [comment]
thanks for the quick response! is there a more general composing library out there that you like?

**Comment by jneen** [comment]
I guess I'm not sure what you mean by composing. The pretty printer you mentioned is a very simple recursive traversal of the nested list, shouldn't need a whole library.

**Comment by bcherny** [comment]
So reading through the docs a bit more, I think was confused about what parsimmon is for. I though it was a general purpose parser, and could parse stuff like "A < 20 and B > 10". That doesn't seem to be the case.

**Comment by jneen** [comment]
That is in fact what parsimmon is for. :confused:

**Comment by bcherny** [comment]
I feel way out of my league with this lib :) I'll play around with actually building something with it, so I can wrap my head around it and ask more specific questions.

**Comment by jneen** [comment]
Okay, let me know :).  It's possible I need to add some stuff or re-emphasize stuff in the README.
