### ISSUE TITLE
A few more examples?

### ISSUE THREAD

**Issue by TGOlson** [jneen/parsimmon#40]
Hey there - first I want to say thanks for the great open source library.

I was wondering if we could get a few examples of different use cases. I'm having a hard time diving in an figuring out exactly what I need. I noticed the initial example on the README using a recursive solution with `lazy` returning `form.or(atom)`. Later in the tips section you mention that generally `lazy` returns a call to `alt`.

I'm sure in the end these are trivial differences, but being new to the idea of combinator parsers, I'd just love to see some simple examples. (btw - I did notice the nice JSON parsing example, but it was a little much to get my head around). Hopefully it's not too much of a hassle - anything would be super helpful.

**Comment by jneen** [comment]
Hi! So two things:

* `x.or(y)` is literally defined as `alt(x, y)` so it's more or less the same
* the only simpler example I have than json right now is the s-expression parser in the README.

**Comment by anko** [comment]
@TGOlson You could also look at [dependents of the parsimmon npm package](https://www.npmjs.com/browse/depended/parsimmon) for inspiration. I wrote a [somewhat more complex S-expression parser](https://github.com/anko/s-expression) using parsimmon for [another project](https://github.com/anko/eslisp).

Do you have a specific idea you're stuck with translating to code?

**Comment by TGOlson** [comment]
Thanks for the replies @jneen and @anko. After spending a little more time with the library things make a lot more sense. Part of the confusion on my end was what the functions actually do, and the other part was the mindset (in general, trying to grasp the mutually recursive parser strategy that pops up a lot).

So, reflecting on that it's probably not your job to teach people how to use a combinator parsing library. Although just to help people get a little footing, it might be nice to see a simple example using `or`, `then`, `skip` and `seq` - a few that I've found myself using a lot. Something like:

```js
var parser = Parsimmon.digits.or(Parsimmon.letters);

parser.parse('something').value; // => 'something';
parser.parse('123').value; // => 123;
```

```js
var parser = Parsimmon.digits.then(Parsimmon.letters);

parser.parse('123something').value; // => 'something';
parser.parse('something123'); // => 'Expected digit at position 1, etc...';
```

```js
var parser = Parsimmon.digits.skip(Parsimmon.letters);

parser.parse('123something').value; // => '123';
parser.parse('123'); // => 'Expected letters at position 3, etc...';
```

Would something like this be something you'd see as worthwhile for this library? I'd definitely be willing to help with PR if you're interested.

**Comment by jneen** [comment]
Sure! A lot of that exists already in the test directory.

**Comment by wavebeem** [comment]
I am already thinking about writing a tutorial for Parsimmon, so I think this should be covered by that.
