### ISSUE TITLE
Parsimmon.between

### ISSUE THREAD

**Issue by hughfdjackson** [jneen/parsimmon#42]
I'm not entirely sure how this would work out in JS-land (what with the lack of currying), but it's always been useful to wrap up parsers in, say, parens: 

```javascript
var between = Parsimmon.between;
var string = Parsimmon.string;
var parens = between(string('('), string(')');

var hiParens = parens(string('hi'));

hiParens.parse('(hi)').value // => 'hi'
```

Thoughts?

**Comment by anko** [comment]
We could have partial application by returning a closure when the third argument isn't present:

```js
var between = function (left, right, middlePerhaps) {
  return middlePerhaps ? left.then(middlePerhaps).skip(right)
                       : function (middle) { return left.then(middle).skip(right) };
};
```

**Comment by wavebeem** [comment]
`P.between(L, R)(X)` doesn't seem like a huge win over `L.then(X).skip(R)` to me, personally. I'd say the beauty of parser combinators is you can easily extend them yourself to fit your needs in your own project :)

**Comment by wavebeem** [comment]
Just a thought, `X.between(L, R)` could be nice, or maybe even `X.between(Y)` which is shorthand for `Y.then(X).skip(Y)`.
