### ISSUE TITLE
not built

### ISSUE THREAD

**Issue by PandaNoir** [jneen/parsimmon#43]
I execute `npm install parsimmon`, but I cannot use Parsimmon.sepBy. `var parsimmon = require('parsimmon');` doesn't contain .sepBy() and .sepBy1(). I guess that parsimmon isn't built for npm now. I want it to be built and available on npm. Please build it.

**Comment by jneen** [comment]
Hi! I haven't had the time to cut a new release since the pull request with `sepBy` was merged.  If you need edge features, you can use a git dependency from npm.

**Comment by PandaNoir** [comment]
Thank you! I'll try it.
