### ISSUE TITLE
Can I write article about README.md of parsimmon in Japanese?

### ISSUE THREAD

**Issue by PandaNoir** [jneen/parsimmon#44]
I was impressed by parsimmon. I want to let many people to know Parsimmon. So I have translated README.md of parsimmon into Japanese.
If you don't want me to publish this translated README.md, I don't publish. Can I write article about README.md of parsimmon in Japanese?

**Comment by jneen** [comment]
yes of course!

**Comment by PandaNoir** [comment]
thanks! the article url is below.
http://pandanoir.seesaa.net/s/article/424224566.html
