### ISSUE TITLE
error.expected not unique

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#46]
When a parse fails and you check the `.expected` field, the array contains many non-unique elements. I would expect this list to be unique.

## Contrived example

```javascript
P.string("a").or(P.string("a")).parse("b")
// => { status: false, index: 0, expected: [ '\'a\'', '\'a\'' ] }
```

## Real world example:

I can probably rephrase my grammar to avoid this somehow, but it seems less than ideal.

```javascript
{ status: false,
  index: 20,
  expected:
   [ 'EOF',
     '\'#\'',
     'whitespace',
     '\'|>\'',
     '\'#\'',
     'whitespace',
     '\'or\'',
     '\'#\'',
     'whitespace',
     '\'and\'',
     '\'#\'',
     'whitespace',
     '\'!=\'',
     '\'#\'',
     'whitespace',
     '\'=\'',
     '\'#\'',
     'whitespace',
     '\'<=\'',
     '\'#\'',
     'whitespace',
     '\'<\'',
     '\'#\'',
     'whitespace',
     '\'>=\'',
     '\'#\'',
     'whitespace',
     '\'>\'',
     '\'#\'',
     'whitespace',
     '\'~\'',
     '\'#\'',
     'whitespace',
     '\'++\'',
     '\'#\'',
     'whitespace',
     '\'-\'',
     '\'#\'',
     'whitespace',
     '\'+\'',
     '\'#\'',
     'whitespace',
     '\'/\'',
     '\'#\'',
     'whitespace',
     '\'*\'',
     '\'#\'',
     'whitespace',
     '\'[\'',
     '\'.\'',
     '\'#\'',
     'whitespace' ] }
```

**Comment by mikebolt** [comment]
Should be fixed in pull request #53 . Please test it with your real world example to make sure that it works for you.

**Comment by jneen** [comment]
We're working on a fix, but in the meanwhile - what this means is that your parser is checking for the same things over and over again at the same spot.  A way to avoid this is to left-factor stuff:

``` js
// from this
alt(seq(a, b), seq(a, c))

// to this
seq(a, alt(b, c))
```

**Comment by wavebeem** [comment]
Thanks. I think I have some time to test this tonight. I just need to remove my code which does the sort|uniq combo.

**Comment by wavebeem** [comment]
@mikebolt This seems to fix it. Here's the new output:
<img width="397" alt="screen shot 2016-01-03 at 9 22 21 pm" src="https://cloud.githubusercontent.com/assets/176815/12083882/223ed82c-b260-11e5-9da7-07e5ca7687b6.png">

@jneen I could left factor it, but spacing is introduced with lower level combinators and it's hard to even tell they're involved at the level where they're getting combined here.

**Comment by wavebeem** [comment]
I'm not keen on changing the public API in order to facilitate this, so I'm thinking of adding a "sorted unique concat"-type function for adding items to the expected set, rather than maintaining a `expectedSet` alongside the `expected` array.
