### ISSUE TITLE
Allow parse with offset

### ISSUE THREAD

**Issue by mizunashi-mana** [jneen/parsimmon#52]
Now, `parse` method is received one target string.

However, I want to give with offset, such as:

```javascript
var result = parser.parse("target string!", 7);
```

It seems not difficult to change, and is compatible.  How's this?

**Comment by PandaNoir** [comment]
I think that `"target string!".slice(7)` can solve this problem. Is there a merit of parse with offset?

```
var result = parser.parse("target string!".slice(7));
```

**Comment by mizunashi-mana** [comment]
yeah, actually, I know this sample.  And, I use now:

```javascript
Parser.prototype.myparse = function(target, startpos, endpos) {
  return this.parse(target.slice(startpos, endpos));
}
```

This issue is a suggestion rather than solving problems.
This change seems to do not have problems.

Change parts will be small, and compatible with older version.

I have some solutions, so, this issue is not necessarily.

**Comment by PandaNoir** [comment]
日本人の方でしたか。英語併記で日本語で話します。
"target string!".slice(7)を渡すことで解決できるのに敢えて追加することは冗長かと。確かにmyparseを使えば短くかけます。が、"target string!".slice(7)を渡せばプログラムを見て「ああ、文字列を切ってパースしてるのか」と分かりやすくなります。また、コードの柔軟性も今のままで充分です。

parse("target string!", 7)にこれらを犠牲にしてまで実装する意義をあまり感じません。

`"target string!".slice(7)` can solve problem. So this addition seems useless.

I agree that parse with offset shorten codes. However, ` .parse("target string!".slice(7))` more clearly shows that you cut and pass string to `.parse()`. In addition, `.parse()` is so powerful that ` .parse()` can replace `.myparse()`.

I think that merit of `.parse("target string!", 7)` isn't over these expressive power of `.parse()`.

**Comment by mizunashi-mana** [comment]
作者さんが日本人でなく、特別日本のユーザーが多いとは思えないので、英語オンリーでいきたいです。
I would like to use only English, because owner is not Japanese and there are not many Japanese users especially.

```javascript
_.parse = function(stream) {
    if (typeof stream !== 'string') {
      throw new Error('.parse must be called with a string as its argument');
    }
    var result = this.skip(eof)._(stream, 0);
    ...
```

This is the code of `parse` method.  Parsimmon's parser is actually received string and index.
But, parse method gives `0` as index to parser for useful.

This is helpful to be black box.  This is good as default action.  But, I think it should be able to specify.

I suggested such as changes:

```javascript
_.parse = function(stream, index) {
    if (typeof stream !== 'string') {
      throw new Error('.parse must be called with a string as its first argument');
    }
    if (index !== undefined && typeof index !== 'number') {
      throw new Error('.parse must be called with a number as its second argument');
    }
    var index_s = index || 0;
    var result = this.skip(eof)._(stream, index_s);
    ...
```

**Comment by PandaNoir** [comment]
Parsimmon needs processing index to parse. However, this isn't for users. So I think Parsimmon intentionally conceals processing index. Actually, in most cases `.parse()` works well without offset.

It is natural that `.parse()` accepts one string argument. "Make each program do one thing well". I think we should separate `.parse()` and `.slice()`.

**Comment by mizunashi-mana** [comment]
Hmm... ok, i see.

Let I go with that, thx.
