### ISSUE TITLE
Expose line and column locations on .mark?

### ISSUE THREAD

**Issue by anko** [jneen/parsimmon#54]
[PEG.js](http://pegjs.org/) and [Jison](http://zaach.github.io/jison/docs/) give locations not only as a character offset but also as line and column numbers. These would help make errors human-readable and are necessary for various other tools e.g. [source maps](https://github.com/mozilla/source-map).

Calculating line and column positions of everything after parsing has finished mixes concerns and is inefficient.

Could parsimmon have e.g. an option passed to `.parse` that would calculate and attach line and column numbers to the objects produced by a `.mark`? Or maybe a new `.markDescriptive` could do that itself? (I'm speculating because I don't yet understand how they work internally.)

A quick search says something like this was discussed in 2014 https://github.com/jneen/parsimmon/pull/23#issuecomment-40158775, but nothing seems to have stuck.

**Comment by wavebeem** [comment]
The regex and custom parsers seem like it would make it hard to keep that
information reliable, but I agree that it's really important to have. I've
spent a lot of energy manually performing conversions at various points in
my parser for Squiggle. It would be really great to have. I guess maybe
after text is consumed the parser could run through it again for new lines
and update the line and column information? Not sure if there's a better
way.
