### ISSUE TITLE
Why does exist assertParser()?

### ISSUE THREAD

**Issue by pandanoir** [jneen/parsimmon#59]
Hi.

Some methods use assertParser, but other methods, such as .seq(), .or() and .next() don't use it. I think they have to call assertParser() because they accept Parser.

assertParser isn't necessary? Or some methods should use it?

**Comment by anko** [comment]
I think asserting correct types of argument is good. For users, it helps catch errors earlier and makes the implementation more robust. For developers, it documents what is happening.
