### ISSUE TITLE
Enhancement: Add Parsimmon.flatSeq

### ISSUE THREAD

**Issue by bcherny** [jneen/parsimmon#64]

**Comment by anko** [comment]
Do you mean a version of `seq` that flattens the arrays in its input into one?

**Comment by bcherny** [comment]
In its output - flatSeq:seq :: flatMap:map

**Comment by wavebeem** [comment]
@bcherny can you provide an example of where this is useful, please?

**Comment by bcherny** [comment]
I forget the original use case :) But modifying the example from the readme, say I want to implement a tokenizer (ignoring the structure of the program). I'd need to sprinkle in a few `flatten` calls:

```js
const Parsimmon = require('parsimmon')
const _ = require('lodash')

var regex = Parsimmon.regex;
var string = Parsimmon.string;
var optWhitespace = Parsimmon.optWhitespace;
var lazy = Parsimmon.lazy;
var seq = Parsimmon.seq

function lexeme(p) { return p.skip(optWhitespace); }

var lparen = lexeme(string('('));
var rparen = lexeme(string(')'));

var expr = lazy('an s-expression', function() { return form.or(atom) });

var number = lexeme(regex(/[0-9]+/).map(parseInt));
var id = lexeme(regex(/[a-z_]\w*/i));

var atom = number.or(id);
var form = seq(lparen, expr.many().map(a => _.flatten(a)), rparen).map(a => _.flatten(a));

expr.parse('3').value // => 3
expr.parse('(add (mul 10 (add 3 4)) (add 7 8))').value
  // => ['add', 'mul', 10, 'add', 3, 4, 'add', 7, 8]
```

With `flatSeq`, I could simplify to:

```js
var form = flatSeq(lparen, expr.many(), rparen);
```

Does that make sense?

**Comment by wavebeem** [comment]
@bcherny It does make sense, but it doesn't seem particularly like the point of Parsimmon to produce just a tokenizer, so I think I would want to see a different use case to be convinced of adding this feature.

**Comment by bcherny** [comment]
Sounds good to me. I'll comment back here if I run into a good use case in the future.

**Comment by wavebeem** [comment]
Cool! Thanks :+1:
