### ISSUE TITLE
P.alt backtracing question

### ISSUE THREAD

**Issue by freekh** [jneen/parsimmon#73]
Hey!
The doc says P.alt is backtracking, however it doesn't appear to be the case here. 
To be clear: the way I understand 'backtracking' is that if the first parser fails on input, the next parser will be tried on the **same** input.
I am not a 100% certain I understand the docs correctly so just wanted to check if this is the correct understanding before giving you repro steps and/or a PR fixing it (I have a pretty big grammar so it will take me some time to give nice repro steps...).

**Comment by wavebeem** [comment]
That's totally the case! I've made an example program to help demonstrate backtracking.

https://gist.github.com/wavebeem/2b42f68b8721fd7bbc9882a98759f8d4

<img width="330" alt="screen shot 2016-06-23 at 09 09 41" src="https://cloud.githubusercontent.com/assets/176815/16310658/41da3a20-3922-11e6-83c8-4c4ec6f65177.png">

**Comment by freekh** [comment]
Thanks for the update & double so for the example (I hadn't noticed P.of -- seems like that might be a good way to debug)! 

I need to have a closer look at what I am doing then :)
I'll update this issue when I either have figured it out, given up or got some repro steps :)
Probably tomorrow or early next week.

My project is very much work in progress, but if you're curious this is the parser: https://github.com/freekh/tasitc/blob/master/code/lang/parser/parse.js

**Comment by freekh** [comment]
Oh, and I should add: nice job on parsimmon in general :)

**Comment by wavebeem** [comment]
I would love to look if I had more time right now. For now, please investigate a bit more and report back with something.

There's definitely some work that can be done here in the future for making debugging Parsimmon easier. Perhaps in the future a little "inspector" like this can be added as part of Parsimmon.

Thanks for your appreciation, but I humbly defer that most of the work was not done by me — I'm just the new maintainer.

**Comment by freekh** [comment]
Will do & of course wavebeem != jneen (sorry about that) :)

**Comment by wavebeem** [comment]
Hi @freekh! I'm going to assume this helped. If you think you've found a bug in the backtracking algorithm, please leave another comment here!
