### ISSUE TITLE
Regexp vs regex

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#84]
Given that JS calls them `RegExp`, I think there should be a `P.regexp` function, and `P.regex` can just become a deprecated alias for it.

**Comment by jneen** [comment]
I...

:<

They're called "regexes" - I pretty vehemently disagree with javascript's naming.

**Comment by jneen** [comment]
I'd be happy with an alias, but please don't deprecate `P.regex`.

**Comment by wavebeem** [comment]
fwiw it's not actually marked as deprecated in the documentation. I plan on keeping it.

**Comment by anko** [comment]
Some data:

 - [The ECMAScript spec calls them "RegExp"](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-regexp-regular-expression-objects), never mentioning "regex".
 - Both terms are in common colloquial usage. [The Wikipedia article "Regular expression"](https://en.wikipedia.org/wiki/Regular_expression) lists both words. There are 6,920,000 Google results for `"regex"` and 4,360,000 for `"regexp"`.
 - In books, "regexp" is used a tiny bit more, [according to Google Ngram Viewer](https://books.google.com/ngrams/graph?content=regex%2Cregexp&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Cregex%3B%2Cc0%3B.t1%3B%2Cregexp%3B%2Cc0).

So either or both seems okay.
