### ISSUE TITLE
Parsimmon.alt(a, b) vs Parsimmon.alt(b, a)

### ISSUE THREAD

**Issue by SomeHats** [jneen/parsimmon#86]
Hello! I think there might be some issue with `Parsimmon.alt`'s backtracing.

My understanding is that if `Parsimmon.alt(a, b)` succeeds, then `Parsimmon.alt(b, a)` should succeed, but that seems not to be that case. 
https://tonicdev.com/575832c9c91caa1300f7bad6/577e7e356d5f74130004bae8 shows a couple of cases where things behave surprisingly. I would expect all of the test cases there to parse successfully.

Thank you for your awesome work maintaining this :)

**Comment by wavebeem** [comment]
Hi @SomeHats!

Unlike some other parsers, it's not true that you can freely reorder a `P.alt` in Parsimmon.

```js
> P.alt(P.string('a'), P.string('ab')).parse('ab')
{ status: false,
  index: { offset: 1, line: 1, column: 2 },
  expected: [ 'EOF' ] }

> P.alt(P.string('ab'), P.string('a')).parse('ab')
{ status: true, value: 'ab' }
```

If two parsers start with the same prefix, you need to put the "longer" one first. Parsimmon simply chooses the first parser that succeeds in the `P.alt` list, so if there's extra characters after using it, you have an error.

This isn't the first time I've seen someone confused by this behavior, so I think maybe it needs further explanation in the README.

**Comment by SomeHats** [comment]
Thanks for the speedy reply :D

I see! That makes sense.

I think the problem I was having was with using `sepBy` rather than `sepBy1` - `sepBy` can match nothing, so that's the "shorter" parser. 

Thanks for your help :)

**Comment by wavebeem** [comment]
Happy to help. I'm opening an issue to provide additional README details.
