### ISSUE TITLE
build is empty

### ISSUE THREAD

**Issue by banacorn** [jneen/parsimmon#99]
> Parsimmon supports IE7 and newer browsers, along with Node.js. It can be used as a standard Node module through npm, or through build/parsimmon.browser.min.js directly in the browser through a script tag, where it exports a global variable called Parsimmon (you can also use the build/parsimmon.browser.js for local development).

What is the best way to get a release or a distribution of the parsimmon library?

**Comment by wavebeem** [comment]
Ah, I can see how that's confusing. The build directory is populated when I publish to npm. If you want a standalone JavaScript file, you can either download the package through `npm install`, or you can use npmcdn:

https://npmcdn.com/parsimmon/build/parsimmon.browser.js
https://npmcdn.com/parsimmon/build/parsimmon.browser.min.js

I'm leaving this open so I can remember to add this to the README.

**Comment by wavebeem** [comment]
TODO: Link to browser.min.js in the package.json `browser` field so npmcdn URL can simply be `https://npmcdn.com/parsimmon`.

https://github.com/defunctzombie/package-browser-field-spec

**Comment by michaelficarra** [comment]
@wavebeem You may want to consider adding a build artifact to the [GitHub releases](https://github.com/jneen/parsimmon/releases).

**Comment by banacorn** [comment]
Thanks!

**Comment by wavebeem** [comment]
No problem! Thanks for taking the time to report the issue.
